name: trydos_wallet_example
description: تطبيق مثال لعرض وتصميم شاشات المحفظة.
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  trydos_wallet:
    path: ..

flutter:
  uses-material-design: true
