name: trydos_wallet
description: "مكتبة محفظة Trydos - سحب، إيداع، ومعاملات. صفحة البداية وواجهات المحفظة."
version: 0.0.1
homepage: https://gitlab.com/trydos_app/trydos_wallet
repository: https://gitlab.com/trydos_app/trydos_wallet.git

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  dio: ^5.7.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/svg/
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
