name: trydos_wallet
publish_to: none
description: "مكتبة محفظة Trydos - سحب، إيداع، ومعاملات. صفحة البداية وواجهات المحفظة."
version: 0.0.1
homepage: https://gitlab.com/trydos_app/trydos_wallet
repository: https://gitlab.com/trydos_app/trydos_wallet.git

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  dio: ^5.7.0
  socket_io_client: ^3.0.2
  flutter_bloc: ^8.1.6
  image_picker: 1.0.6
  uuid: ^4.5.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  gal: ^2.3.2
  pretty_qr_code: ^3.6.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.3
  pointycastle: ^3.9.1
  flutter_screenutil: ^5.9.0
  cupertino_back_gesture: ^0.1.0
  dotted_border: ^2.1.0
  camera: ^0.11.0+2
  google_mlkit_object_detection: ^0.13.0
  image: ^4.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  fonts:
    - family: Quicksand-Regular
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
    - family: Quicksand-Medium
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
    - family: Quicksand-Bold
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
    - family: Quicksand-Light
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf

