/// Localized strings for the wallet app
/// Supports: English (en), Arabic (ar), Kurdish (ku), Turkish (tr)
class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      // Home Tab
      'home_title': 'Home',
      'total_balance': 'Your Total Balance',
      'add_currency': 'Add Currency',
      'your_total_balance': 'Your Total Balance',
      'records': 'Records',
      'transactions': 'Transactions',
      'no_deposit_requests_yet': 'No deposit requests yet',
      'available_balance': 'Available Balance',
      'all_transactions': 'All Transactions',
      'balance': 'Balance',
      'transaction_history': 'Transaction History',
      'no_transactions': 'No transactions yet',
      'recent_transactions': 'Recent Transactions',
      'view_all': 'View All',
      'your_total_balance_of': 'Your Total {currency} Balance',
      'add_account_of': 'Add {currency} Account',

      // Wallet Tab
      'my_wallet': 'My Wallet',
      'manage_balances': 'Manage your balances and transactions',
      'actions_for': 'Actions for',
      'add_funds': 'Add Funds (Deposit)',
      'deposit': 'Deposit',
      'balance_available': 'Available Balance',
      'no_currencies': 'No currencies available',
      'deposit_requests': 'Deposit Requests',
      'status': 'Status',
      'amount': 'Amount',
      'date': 'Date',
      'invoice': 'Invoice',
      'id': 'ID',
      'bank': 'Bank',
      'fees': 'Fees',
      'tax': 'Tax',
      'approved': 'Approved',
      'reference': 'Reference | ID',

      // Addresses Tab
      'addresses': 'Addresses',
      'my_addresses': 'My Addresses',
      'add_address': 'Add Address',
      'copy': 'Copy',
      'copied': 'Copied',
      'no_addresses': 'No addresses yet',

      // Settings Tab
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'Select Language',
      'about': 'About',
      'about_us': 'About Us',
      'terms_conditions': 'Terms & Conditions',
      'legal_information': 'Legal Information',
      'share_app': 'Share App',
      'version': 'Version',
      'logout': 'Logout',
      'personal_information': 'Personal Information',
      'account_information': 'Account Information',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'account_status': 'Account Status',
      'two_factor_authentication': 'Two Factor Authentication',
      'member_since': 'Member Since',
      'verified': 'Verified',
      'not_provided': 'Not provided',
      'active': 'Active',
      'disabled': 'Disabled',
      'enabled': 'Enabled',
      'registered': 'Registered',
      'unprotected_account_limited_access':
          'Unprotected Account | Limited Access',
      'weekly_transfer_volume': 'WEEKLY TRANSFER VOLUME',
      'usd_renew': 'USD | RENEW',
      'fri_1010': 'FRI 10:10',
      'protect_account_full_access': 'Protect Your Account | Full Access',
      'secure_account_safe_transactions':
          'KEEP YOUR ACCOUNT SECURE, ENSURE SAFE TRANSACTIONS',
      'protect_verify_now': 'Protect & Verify Now',
      'id_label': 'ID',
      'add_photo': 'Add Photo',
      'active_session': 'Active Session',
      'profile_photo': 'Profile Photo',
      'add_profile_photo': 'Add Profile Photo',
      'edit_profile_photo': 'Edit Profile Photo',
      'choose': 'Choose',
      'take_photo': 'Take Photo',
      'remove': 'Remove',
      'save': 'Save',
      'no_photos': 'No photos available',
      'permission_camera_required':
          'Camera permission is required to take a photo.',
      'permission_gallery_required':
          'Photos permission is required to choose an image.',
      'camera_unavailable': 'Camera unavailable',
      'preview_crop': 'Preview & Crop',
      'crop': 'Crop',
      'use_photo': 'Use Photo',

      // Request Flow
      'payment_request': 'Payment Request',
      'generate_request': 'Generate Request',
      'requesting': 'Requesting...',
      'valid_until': 'Valid Until',
      'note': 'Note',
      'select_purpose_request': 'Select Purpose Of Money Request',
      'cannot_use_after_expiry':
          'Will Not Be Able To Use The Code After Its Expiry Time',
      'purpose_of_request': 'Purpose Of Money Request',
      'always': 'Always',
      'minute_1': '1 Minute',
      'minutes_3': '3 Minute',
      'minutes_15': '15 Minute',
      'hour_1': '1 Hour',
      'hours_24': '24 Hour',
      'work_partnership': 'Work/Partnership',
      'service_fees': 'Service Fees',
      'home_rent': 'Home Rent',
      'office_shop_rent': 'Office / Shop Rent',
      'deposit_request': 'Deposit Request',
      'enter_amount': 'Enter Amount',
      'enter_reference': 'Enter Reference | ID',
      'enter_note_receiver': 'Enter Your Note To See On Receiver Account',

      // Send Flow
      'transfer_send': 'Transfer | Send',
      'sender_account': 'Sender Account',
      'send_to': 'Send To',
      'recipient_account': 'Recipient Account',
      'recipient_phone': 'Recipient Phone',
      'enter_account_or_phone': 'Enter Account or Phone',
      'recipient_name_id': 'Recipient Name | ID',
      'recipient_id_num': 'Recipient ID Number',
      'amount_to_be_sent': 'Amount to be sent',
      'purpose_of_send': 'Purpose of send',
      'money_sent_success': 'Money sent successfully',
      'transaction_failed': 'Transaction failed',
      'receipt': 'Receipt',

      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'retry': 'Retry',
      'kyc_rescan': 'Rescan',
      'ok': 'OK',
      'safe': 'Safe',
      'powered_by': 'Powered By',
      'failed_to_load': 'Failed to load',
      'try_again': 'Try again',
      'success': 'Success',
      'source_bank': 'Source Bank',
      'select_bank': 'Select a bank...',
      'load_more': 'Load more',
      'amount_label': 'Amount',
      'complete_form_deposit': 'Complete the form to request a deposit.',
      'deposit_symbol': 'Deposit',
      'fee_label': 'Fee:',
      'tax_label': 'Tax:',
      'you_receive': 'You Receive:',
      'proof_of_transfer': 'Proof of Transfer',
      'click_to_upload': 'Click to upload image',
      'upload_success_msg': 'Upload successful',
      'change_image': 'Change image',
      'uploading_msg': 'Uploading...',
      'confirm_upload': 'Confirm upload',
      'confirm_deposit_label': 'Confirm Deposit',
      'deposit_request_submitted': 'Deposit request submitted successfully',
      'deposit_completed_success': 'Deposit completed successfully',
      'failed_to_submit_deposit': 'Failed to submit deposit request',
      'failed_to_load_banks': 'Failed to load banks',
      'page': 'Page',
      'of': 'of',
      'done': 'Done',
      'copy_clipboard': 'Copied to clipboard',
      'failed_to_save': 'Failed to save QR Card.',
      'saved_successfully': 'QR Card saved to gallery successfully!',
      'download': 'Download',
      'share': 'Share',
      'account_name': 'Account Name',
      'account_number': 'Account Number',
      'date_time': 'Date & Time',
      'type': 'Type',
      'succeeded': 'Succeeded',
      'american_dollars': 'American Dollars',
      'until': 'until',
      'payment_request_for': 'Payment Request for {amount} {currency}',
      'main_sub_account': 'Main',
      'deposit_type': 'Deposit',
      'withdrawal_type': 'Withdrawal',
      'refund_type': 'Refund',
      'order_type': 'Order',
      'invoice_type': 'Invoice',
      'receipt_footer_msg':
          'You Can Receive The Money Through All Our Centers, Or You Can Download Our Application, Open An Account, Use The Money, And Benefit From All The Services.',
      'statistic': 'Statistic',
      'info': 'Info',
      'scan_qr_msg': 'Read The Code On The Opposite Side To Take Action',
      'or_choose': 'Or Choose',
      'send_pay_cash': 'Send | Pay | Cash Withdrawal',
      'send_money_pay': 'Send Money Or Pay',
      'receive_charge_request': 'Receive | Charge My Account | Request',
      'charge_wallet_msg': 'Charge Your Wallet Account Money',
      'splash_safe': 'safe...',
      'splash_easy': 'easy...',
      'splash_transaction': 'transaction...',
      'splash_payment': 'payment...',
      'acc_copied_msg': 'Account number copied to clipboard',
      'my_receipt_qr': 'My Receipt Account QR',
      'request': 'Request',
      'back': 'Back',
      'send_pay_cash_upper': 'SEND | PAY | CASH WITHDRAWAL',
      'transfer_send_msg': 'Send | Transfer Money To rdb | cash | bank',
      'history': 'History',
      'cash_withdrawal': 'Cash Withdrawal',
      'withdrawal_msg': 'Withdrawal Via Our Centers Or Agents',
      'nearby_centers': 'Nearby Centers',
      'bill_payments': 'Bill Payments',
      'pay_invoice_msg': 'Pay Invoice | Bill |',
      'jan': 'Jan',
      'feb': 'Feb',
      'mar': 'March',
      'apr': 'April',
      'may': 'May',
      'jun': 'June',
      'jul': 'July',
      'aug': 'August',
      'sep': 'Sept',
      'oct': 'Oct',
      'nov': 'Nov',
      'dec': 'Dec',
      'invalid_amount': 'Invalid Amount',
      'insufficient_balance': 'Insufficient Balance',
      'incorrect_account_msg':
          'Incorrect account number. It must be longer than 7 characters and include -',
      'account_not_found_msg': 'Account not found',
      'account_lookup_failed_msg': 'Failed to verify account',
      'phone_min_digits_msg': 'Phone number must be at least 7 digits',
      'recipient_account_num': 'Recipient Account Number',
      'recipient_phone_num': 'Recipient Phone Number',
      'paste': 'Paste',
      'office': 'Office',
      'enter_recipient_acc': 'Enter Recipient Account Number',
      'enter_recipient_phone': 'Enter Recipient Phone Number',
      'enter_recipient_name': 'Enter Recipient Name & Surname Exact ID',
      'enter_recipient_id': 'Enter Recipient ID NUMBER',
      'recipient_name_hint': 'Mohamad Ramzi Katmawi',
      'recipient_id_hint': 'ID Card Or Passport Or Driving License Number',
      'enter': 'Enter ',
      'or': ' Or    ',
      'edit': 'Edit',
      'sending': 'Sending...',
      'send_deposits': 'Send Deposits',
      'expired_code': 'Expired Code ( Time Expired )',
      'request_cancelled': 'Request Cancelled',
      'request_fulfilled': 'Request Already Fulfilled',
      'request_inactive': 'Request Is Not Active',
      'reference_id': 'Reference | ID',
      'minutes_until': ' Minutes Until ',
      'select_purpose_send': 'Select Purpose Of Money Send',
      'select_currency_to_send_msg':
          'Please select a currency before scanning to send',
      'send_label': 'Send',
      'receive_label': 'Receive',
      'chart': 'Chart',

      // KYC
      'kyc_identity_verification': 'Identity Verification !',
      'kyc_protect_account': 'Protect Your Account & Get Full Access',
      'kyc_verify_description':
          'We Need To Verify Your Identity Once To Protect Your Account From Fraud And Comply With Security Regulations One-Time Process To Confirm That You. It Helps Keep Your Account Secure, Prevents Fraud, And Ensures Safe Transactions Just Like Showing Your ID When Opening A Bank Account.',
      'kyc_privacy_safe': 'Your Privacy Is Completely Safe',
      'kyc_start_verification': 'Start Verification',
      'kyc_later_limited': 'Later, Use The Limited Version',
      'kyc_live_detection_id': 'Live Detection Your ID',
      'kyc_start_live_detection': 'Start Live Detection Your ID',
      'kyc_id_matching_not_correct': 'ID Matching With Your Photo Not Correct',
      'kyc_id_discrepancy':
          'We Noticed A Discrepancy In The Image And There Is Also Doubt About The Personal Identity.',
      'kyc_try_again_correction': 'Try Again With The Correction',
      'kyc_rematch': 'Rematch',
      'kyc_live_face_detection': 'Live Face Detection',
      'kyc_face_centered':
          'Please Keep Your Face Centered On The Screen And Facing Forward',
      'kyc_live_id_done': 'Live ID Detection Done',
      'kyc_information_detected': 'Information Detected',
      'kyc_id_type': 'Id Type',
      'kyc_country': 'Country',
      'kyc_name': 'Name',
      'kyc_national_number': 'National Number',
      'kyc_birthday': 'Birthday',
      'kyc_correct_next': 'Correct, Next',
      'kyc_contact_you_soon': 'Will Contact With You Soon',
      'kyc_incorrect_try_again': 'Incorrect, Try Again',
      'kyc_success_verification': 'Success Verification !',
      'kyc_full_access': 'You Have Enjoy With Our Full Access',
      'kyc_video_call_from_our_side': 'Video Call From Our Side',
      'kyc_ai_call_description':
          'A 15-Second AI Call, Fully Encrypted To Ensure Your Account Is Secure',
      'kyc_start_video_call': 'Start Video Call',
      'kyc_later': 'Later',
      'kyc_end_video_call': 'End Video Call',
      'kyc_front_side': 'Front Side ',
      'kyc_back_side': 'Back Side ',
      'kyc_verify_identity_btn': 'Verify Identity',
      'kyc_low_light_warning': 'Low light! Please improve lighting to continue',
      'kyc_align_id': 'Align your ID card within the frame',
      'kyc_camera_error': 'Camera unavailable. Check permissions.',
      'kyc_flip_to_back': 'Flip your ID — align the back side within the frame',
      'kyc_too_far': 'Move the document closer to the camera',
      'kyc_too_close': 'Move the document a little farther from the camera',
      'kyc_liveness_turn_left': 'Turn your face to the left',
      'kyc_liveness_turn_right': 'Turn your face to the right',
      'kyc_liveness_look_up': 'Raise your face a little up',
      'kyc_liveness_blink': 'Please blink both eyes',
      'kyc_align_face': 'Position your face in the frame',
      'kyc_liveness_verifying': 'Verifying liveness...',
      'kyc_liveness_done': 'Liveness verified successfully',
      'kyc_liveness_failed': 'Liveness check failed. Please try again.',
      'kyc_camera_auto_closed': 'Camera closed after 30 seconds of no activity',
      'kyc_reopen_camera': 'Reopen Camera',
      'no_internet_title': 'No Internet Connection',
      'no_internet_subtitle':
          'Please check your internet connection and make sure you are connected to Wi-Fi or mobile data.',
    },
    'ar': {
      // Home Tab
      'home_title': 'الرئيسية',
      'total_balance': 'إجمالي رصيدك',
      'add_currency': 'إضافة عملة',
      'chart': 'مخطط',
      'available_balance': 'الرصيد المتاح',
      'records': 'السجلات',
      'transactions': 'المعاملات',
      'no_deposit_requests_yet': 'لا توجد طلبات إيداع حتى الآن',
      'all_transactions': 'جميع المعاملات',
      'your_total_balance': 'إجمالي رصيدك',
      'balance': 'الرصيد',
      'transaction_history': 'سجل المعاملات',
      'no_transactions': 'لا توجد معاملات حتى الآن',
      'recent_transactions': 'المعاملات الأخيرة',
      'view_all': 'عرض الكل',
      'your_total_balance_of': 'إجمالي رصيد {currency} الخاص بك',
      'add_account_of': 'إضافة حساب {currency}',

      // Wallet Tab
      'my_wallet': 'محفظتي',
      'manage_balances': 'إدارة أرصدتك والمعاملات',
      'actions_for': 'الإجراءات لـ',
      'add_funds': 'إضافة أموال (إيداع)',
      'deposit': 'إيداع',
      'balance_available': 'الرصيد المتاح',
      'no_currencies': 'لا توجد عملات متاحة',
      'deposit_requests': 'طلبات الإيداع',
      'status': 'الحالة',
      'amount': 'المبلغ',
      'date': 'التاريخ',
      'pending': 'قيد الانتظار',
      'completed': 'مكتمل',
      'failed': 'فشل',
      'withdrawal': 'سحب',
      'refund': 'استرداد',
      'order': 'طلب',
      'invoice': 'فاتورة',
      'id': 'المعرف',
      'bank': 'البنك',
      'fees': 'الرسوم',
      'tax': 'الضريبة',

      // Addresses Tab
      'addresses': 'العناوين',
      'my_addresses': 'عناويني',
      'add_address': 'إضافة عنوان',
      'copy': 'نسخ',
      'copied': 'تم النسخ',
      'no_addresses': 'لا توجد عناوين حتى الآن',

      // Settings Tab
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'اختر اللغة',
      'about': 'حول',
      'about_us': 'من نحن',
      'terms_conditions': 'الشروط والأحكام',
      'legal_information': 'المعلومات القانونية',
      'share_app': 'مشاركة التطبيق',
      'version': 'الإصدار',
      'logout': 'تسجيل الخروج',
      'personal_information': 'المعلومات الشخصية',
      'account_information': 'معلومات الحساب',
      'email': 'البريد الإلكتروني',
      'phone_number': 'رقم الهاتف',
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الأخير',
      'account_status': 'حالة الحساب',
      'two_factor_authentication': 'المصادقة الثنائية',
      'member_since': 'عضو منذ',
      'verified': 'موثق',
      'not_provided': 'غير متوفر',
      'active': 'نشط',
      'disabled': 'معطل',
      'enabled': 'مفعل',
      'registered': 'مسجل',
      'unprotected_account_limited_access': 'حساب غير محمي | صلاحيات محدودة',
      'weekly_transfer_volume': 'حجم التحويل الأسبوعي',
      'usd_renew': 'USD | تجديد',
      'fri_1010': 'الجمعة 10:10',
      'protect_account_full_access': 'احمِ حسابك | وصول كامل',
      'secure_account_safe_transactions':
          'حافظ على أمان حسابك، وضمن معاملات آمنة',
      'protect_verify_now': 'احمِ الحساب وتحقق الآن',
      'id_label': 'المعرّف',
      'add_photo': 'إضافة صورة',
      'active_session': 'جلسة نشطة',
      'profile_photo': 'الصورة الشخصية',
      'add_profile_photo': 'إضافة صورة شخصية',
      'edit_profile_photo': 'تعديل الصورة الشخصية',
      'choose': 'اختيار',
      'take_photo': 'التقاط صورة',
      'remove': 'إزالة',
      'save': 'حفظ',
      'no_photos': 'لا توجد صور متاحة',
      'permission_camera_required': 'مطلوب إذن الكاميرا لالتقاط صورة.',
      'permission_gallery_required': 'مطلوب إذن الصور لاختيار صورة.',
      'camera_unavailable': 'الكاميرا غير متاحة',
      'preview_crop': 'معاينة وقص',
      'crop': 'قص',
      'use_photo': 'استخدام الصورة',

      // Request Flow
      'payment_request': 'طلب دفع',
      'generate_request': 'إنشاء طلب',
      'requesting': 'جاري الطلب...',
      'valid_until': 'صالح حتى',
      'note': 'ملاحظة',
      'select_purpose_request': 'اختر الغرض من طلب المال',
      'cannot_use_after_expiry':
          'لن يتم التمكن من استخدام الرمز بعد انتهاء وقت الصلاحية',
      'purpose_of_request': 'الغرض من طلب المال',
      'always': 'دائماً',
      'minute_1': '1 دقيقة',
      'minutes_3': '3 دقائق',
      'minutes_15': '15 دقيقة',
      'hour_1': 'ساعة واحدة',
      'hours_24': '24 ساعة',
      'work_partnership': 'عمل / شراكة',
      'service_fees': 'رسوم الخدمة',
      'home_rent': 'إيجار منزل',
      'office_shop_rent': 'إيجار مكتب / محل',
      'deposit_request': 'طلب إيداع',
      'enter_amount': 'أدخل المبلغ',
      'enter_reference': 'أدخل المرجع | المعرف',
      'enter_note_receiver': 'أدخل ملاحظتك ليراها حساب المستلم',

      // Send Flow
      'transfer_send': 'تحويل | إرسال',
      'sender_account': 'حساب المرسل',
      'send_to': 'إرسال إلى',
      'recipient_account': 'حساب المستلم',
      'recipient_phone': 'رقم هاتف المستلم',
      'enter_account_or_phone': 'أدخل الحساب أو رقم الهاتف',
      'recipient_name_id': 'اسم المستلم | المعرف',
      'recipient_id_num': 'رقم المعرف للمستلم',
      'amount_to_be_sent': 'المبلغ المراد إرساله',
      'purpose_of_send': 'الغرض من الإرسالية',
      'money_sent_success': 'تم إرسال الأموال بنجاح',
      'transaction_failed': 'فشلت المعاملة',
      'receipt': 'إيصال',

      // Common
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'retry': 'إعادة محاولة',
      'kyc_rescan': 'إعادة المسح',
      'ok': 'حسناً',
      'safe': 'آمن',
      'powered_by': 'مدعوم من',
      'failed_to_load': 'فشل التحميل',
      'try_again': 'حاول مرة أخرى',
      'success': 'نجح',
      'source_bank': 'البنك المصدر',
      'select_bank': 'اختر بنكاً...',
      'load_more': 'تحميل المزيد',
      'amount_label': 'المبلغ',
      'complete_form_deposit': 'أكمل النموذج لطلب الإيداع.',
      'deposit_symbol': 'إيداع',
      'fee_label': 'الرسوم:',
      'tax_label': 'الضريبة:',
      'you_receive': 'ستستلم:',
      'proof_of_transfer': 'إثبات الحوالة',
      'click_to_upload': 'اضغط لرفع صورة',
      'upload_success_msg': 'تم الرفع بنجاح',
      'change_image': 'تغيير الصورة',
      'uploading_msg': 'جاري الرفع...',
      'confirm_upload': 'تأكيد الرفع',

      'confirm_deposit_label': 'تأكيد الإيداع',
      'deposit_request_submitted': 'تم تقديم طلب الإيداع بنجاح',
      'deposit_completed_success': 'تم اكتمال الإيداع بنجاح',
      'failed_to_submit_deposit': 'فشل في تقديم طلب الإيداع',
      'failed_to_load_banks': 'فشل في تحميل البنوك',
      'page': 'صفحة',
      'of': 'من',
      'done': 'تم',
      'copy_clipboard': 'نسخ إلى الحافظة',
      'failed_to_save': 'فشل في الحفظ',
      'saved_successfully': 'تم الحفظ بنجاح',
      'download': 'تحميل',
      'share': 'مشاركة',
      'account_name': 'اسم الحساب',
      'account_number': 'رقم الحساب',
      'date_time': 'التاريخ والوقت',
      'type': 'النوع',
      'succeeded': 'نجحت',
      'american_dollars': 'دولارات أمريكية',
      'receipt_footer_msg':
          'يمكنك استلام الأموال من خلال جميع مراكزنا، أو يمكنك تحميل تطبيقنا، وفتح حساب، واستخدام الأموال، والاستفادة من جميع الخدمات.',
      'statistic': 'الإحصائيات',
      'info': 'معلومات',
      'approved': 'مقبول',
      'reference': 'المرجع | المعرف',
      'scan_qr_msg': 'اقرأ الكود في الجهة المقابلة لاتخاذ إجراء',
      'or_choose': 'أو اختر',
      'send_pay_cash': 'إرسال | دفع | سحب نقدي',
      'send_money_pay': 'إرسال أموال أو دفع',
      'receive_charge_request': 'استلام | شحن حسابي | طلب',
      'charge_wallet_msg': 'شحن أموال حساب محفظتك',
      'splash_safe': 'آمن...',
      'splash_easy': 'سهل...',
      'splash_transaction': 'معاملة...',
      'splash_payment': 'دفع...',
      'acc_copied_msg': 'تم نسخ رقم الحساب إلى الحافظة',
      'my_receipt_qr': 'QR حساب الإيصال الخاص بي',
      'request': 'طلب',
      'back': 'رجوع',
      'send_pay_cash_upper': 'إرسال | دفع | سحب نقدي',
      'transfer_send_msg': 'إرسال | تحويل أموال إلى rdb | نقداً | بنك',
      'history': 'السجل',
      'cash_withdrawal': 'سحب نقدي',
      'withdrawal_msg': 'سحب من خلال مراكزنا أو وكلائنا',
      'nearby_centers': 'المراكز القريبة',
      'bill_payments': 'دفع الفواتير',
      'pay_invoice_msg': 'دفع فاتورة | إيصال |',
      'jan': 'يناير',
      'feb': 'فبراير',
      'mar': 'مارس',
      'apr': 'أبريل',
      'may': 'مايو',
      'jun': 'يونيو',
      'jul': 'يوليو',
      'aug': 'أغسطس',
      'sep': 'سبتمبر',
      'oct': 'أكتوبر',
      'nov': 'نوفمبر',
      'dec': 'ديسمبر',
      'invalid_amount': 'مبلغ غير صحيح',
      'insufficient_balance': 'رصيد غير كافٍ',
      'incorrect_account_msg':
          'رقم الحساب غير صحيح. يجب أن يكون أكثر من 7 خانات ويحتوي على -',
      'account_not_found_msg': 'الحساب غير موجود',
      'account_lookup_failed_msg': 'فشل التحقق من الحساب',
      'phone_min_digits_msg': 'رقم الهاتف يجب أن يتكون من 7 أرقام على الأقل',
      'recipient_account_num': 'رقم حساب المستلم',
      'recipient_phone_num': 'رقم هاتف المستلم',
      'paste': 'لصق',
      'office': 'مكتب',
      'enter_recipient_acc': 'أدخل رقم حساب المستلم',
      'enter_recipient_phone': 'أدخل رقم هاتف المستلم',
      'enter_recipient_name': 'أدخل اسم المستلم واللقب تماماً كما في الهوية',
      'enter_recipient_id': 'أدخل رقم هوية المستلم',
      'recipient_name_hint': 'محمد رمزي كتماوي',
      'recipient_id_hint': 'رقم الهوية أو جواز السفر أو رخصة القيادة',
      'enter': 'أدخل ',
      'or': ' أو    ',
      'edit': 'تعديل',
      'sending': 'جاري الإرسال...',
      'send_deposits': 'إرسال الإيداع',
      'expired_code': 'رمز منتهي الصلاحية (الوقت انتهى)',
      'request_cancelled': 'الطلب ملغى',
      'request_fulfilled': 'تم تنفيذ الطلب مسبقاً',
      'request_inactive': 'الطلب غير نشط',
      'reference_id': 'المرجع | المعرف',
      'minutes_until': ' دقائق حتى ',
      'select_purpose_send': 'اختر الغرض من إرسال المال',
      'select_currency_to_send_msg': 'يجب اختيار عملة قبل مسح الباركود للإرسال',
      'send_label': 'إرسال',
      'receive_label': 'استلام',
      'until': 'حتى',
      'payment_request_for': 'طلب دفع بـ {amount} {currency}',
      'main_sub_account': 'الأساسي',
      'deposit_type': 'إيداع',
      'withdrawal_type': 'سحب',
      'refund_type': 'استرداد',
      'order_type': 'طلب',
      'invoice_type': 'فاتورة',

      // KYC
      'kyc_identity_verification': 'التحقق من الهوية !',
      'kyc_protect_account': 'احمِ حسابك واحصل على الوصول الكامل',
      'kyc_verify_description':
          'نحتاج إلى التحقق من هويتك مرة واحدة لحماية حسابك من الاحتيال والامتثال لأنظمة الأمان، وهي عملية لمرة واحدة لتأكيد هويتك. تساعد على إبقاء حسابك آمناً ومنع الاحتيال وضمان المعاملات الآمنة تماماً مثل تقديم هويتك عند فتح حساب مصرفي.',
      'kyc_privacy_safe': 'خصوصيتك آمنة تماماً',
      'kyc_start_verification': 'بدء التحقق',
      'kyc_later_limited': 'لاحقاً، استخدم النسخة المحدودة',
      'kyc_live_detection_id': 'الكشف المباشر عن هويتك',
      'kyc_start_live_detection': 'بدء الكشف المباشر عن هويتك',
      'kyc_id_matching_not_correct': 'الهوية لا تتطابق مع صورتك',
      'kyc_id_discrepancy':
          'لاحظنا وجود تباين في الصورة وهناك أيضاً شك في الهوية الشخصية.',
      'kyc_try_again_correction': 'حاول مرة أخرى مع التصحيح',
      'kyc_rematch': 'إعادة المطابقة',
      'kyc_live_face_detection': 'الكشف المباشر عن الوجه',
      'kyc_face_centered': 'يرجى إبقاء وجهك في وسط الشاشة والنظر للأمام',
      'kyc_live_id_done': 'اكتمل الكشف المباشر عن الهوية',
      'kyc_information_detected': 'المعلومات المكتشفة',
      'kyc_id_type': 'نوع الهوية',
      'kyc_country': 'البلد',
      'kyc_name': 'الاسم',
      'kyc_national_number': 'الرقم الوطني',
      'kyc_birthday': 'تاريخ الميلاد',
      'kyc_correct_next': 'صحيح، التالي',
      'kyc_contact_you_soon': 'سنتواصل معك قريباً',
      'kyc_incorrect_try_again': 'غير صحيح، حاول مرة أخرى',
      'kyc_success_verification': 'تم التحقق بنجاح !',
      'kyc_full_access': 'يمكنك الآن الاستمتاع بالوصول الكامل',
      'kyc_video_call_from_our_side': 'مكالمة فيديو من جانبنا',
      'kyc_ai_call_description':
          'مكالمة ذكاء اصطناعي لمدة 15 ثانية، مشفرة بالكامل لضمان أمان حسابك',
      'kyc_start_video_call': 'بدء مكالمة الفيديو',
      'kyc_later': 'لاحقاً',
      'kyc_end_video_call': 'إنهاء مكالمة الفيديو',
      'kyc_front_side': 'الوجه الأمامي ',
      'kyc_back_side': 'الوجه الخلفي ',
      'kyc_verify_identity_btn': 'التحقق من الهوية',
      'kyc_low_light_warning': 'الإضاءة ضعيفة! يرجى تحسين الإضاءة للمتابعة',
      'kyc_align_id': 'ضع بطاقة الهوية داخل الإطار',
      'kyc_camera_error': 'الكاميرا غير متاحة. تحقق من الأذونات.',
      'kyc_flip_to_back': 'اقلب الهوية — ضع الوجه الخلفي داخل الإطار',
      'kyc_too_far': 'قرّب المستند من الكاميرا',
      'kyc_too_close': 'ابعد المستند قليلاً عن الكاميرا',
      'kyc_liveness_turn_left': 'حرّك وجهك إلى اليسار',
      'kyc_liveness_turn_right': 'حرّك وجهك إلى اليمين',
      'kyc_liveness_look_up': 'ارفع وجهك قليلاً للأعلى',
      'kyc_liveness_blink': 'يرجى الرمش بكلتا العينين',
      'kyc_align_face': 'ضع وجهك داخل الإطار',
      'kyc_liveness_verifying': 'جارٍ التحقق من الحيوية...',
      'kyc_liveness_done': 'تم التحقق من الحيوية بنجاح',
      'kyc_liveness_failed': 'فشل التحقق من الحيوية. حاول مرة أخرى.',
      'kyc_camera_auto_closed':
          'تم إغلاق الكاميرا تلقائياً بعد 30 ثانية دون نشاط',
      'kyc_reopen_camera': 'إعادة فتح الكاميرا',
      'no_internet_title': 'لا يوجد اتصال بالإنترنت',
      'no_internet_subtitle':
          'يرجى التحقق من اتصالك بالإنترنت والتأكد من اتصالك بشبكة Wi-Fi أو بيانات الجوال.',
    },
    'ku': {
      // Home Tab
      'home_title': 'سەرەتا',
      'total_balance': 'کۆی بەروونی تۆ',
      'add_currency': 'موژدە سازی زیادکە',
      'all_transactions': 'هەموو وەرگێڕانەکان',
      'available_balance': 'بەروونی دەستدەست',
      'records': 'تۆمارەکان',
      'transactions': 'وەرگێڕانەکان',
      'no_deposit_requests_yet': 'هێشتا هیچ داواکاری داخواڵێک نیە',
      'balance': 'بەروونی',
      'transaction_history': 'مێژووی وەرگێڕانەکان',
      'no_transactions': 'هیچ وەرگێڕانەی تێدا نیە',
      'recent_transactions': 'وەرگێڕانە نوێیەکان',
      'your_total_balance': 'کۆی بەروونی تۆ',
      'view_all': 'هەمووی ببینە',
      'chart': 'مخطط',
      'your_total_balance_of': 'کۆی باڵانسی {currency} تۆ',
      'add_account_of': 'زیادکردنی هەژماری {currency}',

      // Wallet Tab
      'my_wallet': 'کیسەی من',
      'manage_balances': 'بەڕێوەبردنی بەروونی و وەرگێڕانەکان',
      'actions_for': 'کردارەکان بۆ',
      'add_funds': 'زیادکردنی پارە (داخواڵ)',
      'deposit': 'داخواڵ',
      'balance_available': 'بەروونی دەستدەست',
      'no_currencies': 'موژدە سازێی بەردەست نیە',
      'deposit_requests': 'داواکاری داخواڵ',
      'status': 'دۆخ',
      'amount': 'بەرھەم',
      'date': 'بەرواری',
      'pending': 'چاوەڕۆیان کردن',
      'completed': 'تێچوو',
      'failed': 'شکست',
      'withdrawal': 'ڕاکێشان',
      'refund': 'گێڕانەوە',
      'order': 'داواکاری',
      'invoice': 'وەسڵ',
      'id': 'ناسنامە',
      'bank': 'بانک',
      'fees': 'ڕسوومات',
      'tax': 'باج',
      'approved': 'پەسەندکراوە',
      'reference': 'سەرچاوە | ناسنامە',

      // Addresses Tab
      'addresses': 'ناونیشانەکان',
      'my_addresses': 'ناونیشانەکانی من',
      'add_address': 'زیادکردنی ناونیشان',
      'copy': 'کۆپی',
      'copied': 'کۆپی کرا',
      'no_addresses': 'هیچ ناونیشانی تێدا نیە',

      // Settings Tab
      'settings': 'ڕێکخستنەکان',
      'language': 'زمان',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'زمانی هەڵبژێرە',
      'about': 'دەربارەی',
      'about_us': 'دەربارەی ئێمە',
      'terms_conditions': 'مەرج و ڕێنماییەکان',
      'legal_information': 'زانیاری یاسایی',
      'share_app': 'هاوبەشی ئەپ',
      'version': 'وەشان',
      'logout': 'دەرچوون',
      'personal_information': 'زانیاری کەسی',
      'account_information': 'زانیاری هەژمار',
      'email': 'ئیمەیڵ',
      'phone_number': 'ژمارەی مۆبایل',
      'first_name': 'ناوی یەکەم',
      'last_name': 'ناوی دووەم',
      'account_status': 'دۆخی هەژمار',
      'two_factor_authentication': 'پشتڕاستکردنەوەی دوو هەنگاو',
      'member_since': 'ئەندامە لە',
      'verified': 'پشتڕاستکراوە',
      'not_provided': 'بەردەست نییە',
      'active': 'چالاک',
      'disabled': 'ناچالاک',
      'enabled': 'چالاککراوە',
      'registered': 'تۆمارکراوە',
      'unprotected_account_limited_access':
          'هەژماری نەپارێزراو | دەستگەیشتنی سنووردار',
      'weekly_transfer_volume': 'قەبارەی گواستنەوەی هەفتانە',
      'usd_renew': 'USD | نوێکردنەوە',
      'fri_1010': 'هەینی 10:10',
      'protect_account_full_access': 'هەژمارەکەت بپارێزە | دەستگەیشتنی تەواو',
      'secure_account_safe_transactions':
          'هەژمارەکەت پارێزراو بهێڵەوە، مامەڵەی ئاسایش دڵنیابکە',
      'protect_verify_now': 'ئێستا بپارێزە و پشتڕاستبکەرەوە',
      'id_label': 'ناسنامە',
      'add_photo': 'زیادکردنی وێنە',
      'active_session': 'کۆبوونەوەی چالاک',
      'profile_photo': 'وێنەی پڕۆفایل',
      'add_profile_photo': 'زیادکردنی وێنەی پڕۆفایل',
      'edit_profile_photo': 'دەستکاری وێنەی پڕۆفایل',
      'choose': 'هەڵبژاردن',
      'take_photo': 'وێنە هەبگرە',
      'remove': 'سڕینەوە',
      'save': 'پاشەکەوت',
      'no_photos': 'هیچ وێنەیەک بەردەست نییە',
      'permission_camera_required': 'مۆڵەتی کامێرا پێویستە بۆ گرتنی وێنە.',
      'permission_gallery_required':
          'مۆڵەتی وێنەکان پێویستە بۆ هەڵبژاردنی وێنە.',
      'camera_unavailable': 'کامێرا بەردەست نییە',
      'preview_crop': 'پێشبینین و بڕین',
      'crop': 'بڕین',
      'use_photo': 'بەکارهێنانی وێنە',

      // Request Flow
      'payment_request': 'داواکاری پارەدان',
      'generate_request': 'دروستکردنی داواکاری',
      'requesting': 'جاري داواكردن...',
      'valid_until': 'بەردەستە تا',
      'note': 'تێبینی',
      'select_purpose_request': 'هۆکاری داواکاری پارە هەڵبژێرە',
      'cannot_use_after_expiry':
          'ناتوانی کۆدەکە بەکاربهێنیت دوای بەسەرچوونی کاتەکەی',
      'purpose_of_request': 'هۆکاری داواکاری پارە',
      'always': 'هەمیشە',
      'minute_1': '١ خولەک',
      'minutes_3': '٣ خولەک',
      'minutes_15': '١٥ خولەک',
      'hour_1': '١ کاتژمێر',
      'hours_24': '٢٤ خولەک',
      'work_partnership': 'کار / هاوبەشی',
      'service_fees': 'ڕسوومات خزمەتگوزاری',
      'home_rent': 'کرێی خانوو',
      'office_shop_rent': 'کرێی نووسینگە / دوکان',
      'deposit_request': 'داواکاری داخیڵکردن',
      'enter_amount': 'بڕ بنووسە',
      'enter_reference': 'سەرچاوە | ناسنامە بنووسە',
      'enter_note_receiver': 'تێبینی بنووسە بۆ هەژماری وەرگر',

      // Send Flow
      'transfer_send': 'گواستنەوە | ناردن',
      'sender_account': 'هەژماری نێرەر',
      'send_to': 'ناردن بۆ',
      'recipient_account': 'هەژماری وەرگر',
      'recipient_phone': 'ژمارەی مۆبایلی وەرگر',
      'enter_account_or_phone': 'هەژمار یان ژمارەی مۆبایل بنووسە',
      'recipient_name_id': 'ناوی وەرگر | ناسنامە',
      'recipient_id_num': 'ژمارەی ناسنامەی وەرگر',
      'amount_to_be_sent': 'بڕی پارەی نێردراو',
      'purpose_of_send': 'هۆکاری ناردن',
      'money_sent_success': 'پارەکە بە سەرکەوتوویی نێردرا',
      'transaction_failed': 'مامەڵەکە شکستی هێنا',
      'receipt': 'وەسڵ',

      // Common
      'loading': 'بارکردن...',
      'error': 'هەڵە',
      'retry': 'هەوڵ دووبارە',
      'kyc_rescan': 'دووبارە سکان بکە',
      'ok': 'باشە',
      'safe': 'ئیمن',
      'powered_by': 'پشتگیری',
      'failed_to_load': 'بارکردن شکست',
      'try_again': 'دووبارە هەوڵ بدە',
      'success': 'سەرکەوتوو',
      'source_bank': 'بانکی سەرچاوە',
      'select_bank': 'بانکێ هەڵبژێرە...',
      'load_more': 'زیاتر بەرزبکەرەوە',
      'amount_label': 'بڕی',
      'complete_form_deposit': 'تکایە فۆرمەکە پڕبکەرەوە بۆ داواکاری داخیڵکردن.',
      'deposit_symbol': 'داخیڵکردن',
      'fee_label': 'ڕسوومات:',
      'tax_label': 'باج:',
      'you_receive': 'تۆ وەردەگریت:',
      'proof_of_transfer': 'بەڵگەی گواستنەوە',
      'click_to_upload': 'کلیک بکە بۆ بەرزکردنەوەی وێنە',
      'upload_success_msg': 'بەرزکردنەوە سەرکەوتوو بوو',
      'change_image': 'وێنەکە بگۆڕە',
      'uploading_msg': 'جاری بەرزکردنەوەیە...',
      'confirm_upload': 'بەرزکردنەوە پشتڕاست بکەرەوە',
      'confirm_deposit_label': 'داخیڵکردن پشتڕاست بکەرەوە',
      'deposit_request_submitted': 'داواکاری داخیڵکردن بە سەرکەوتوویی نێردرا',
      'deposit_completed_success': 'داخیڵکردن بە سەرکەوتوویی تەواو بوو',
      'failed_to_submit_deposit': 'ناردنی داواکاری داخیڵکردن شکستی هێنا',
      'failed_to_load_banks': 'بارکردنی بانکەکان شکستی هێنا',
      'page': 'لاپەڕە',
      'of': 'لە',
      'done': 'تەواو',
      'copy_clipboard': 'کۆپی کرا بۆ کلیپبۆرد',
      'failed_to_save': 'پاشکەوتکردن شکستی هێنا',
      'saved_successfully': 'بە سەرکەوتوویی پاشکەوت کرا',
      'download': 'داگرتن',
      'share': 'هاوبەشکردن',
      'account_name': 'ناوی هەژمار',
      'account_number': 'ژمارەی هەژمار',
      'date_time': 'بەروار و کات',
      'type': 'جۆر',
      'succeeded': 'سەرکەوتوو بوو',
      'american_dollars': 'دۆلاری ئەمریکی',
      'receipt_footer_msg':
          'دەتوانیت پارەکە لە ڕێگەی هەموو سەنتەرەكانمانەوە وەربگریت، یان دەتوانیت ئەپڵیکەیشنەکەمان دابەزێنیت، هەژمارێک بكەیتەوە، پارەکە بەکاربهێنیت، و سوود لە هەموو خزمەتگوزارییەکان وەربگریت.',
      'statistic': 'ئامارەكان',
      'info': 'زانیاری',
      'scan_qr_msg':
          'بۆ ئەوەی کردارێک ئەنجام بدەیت، کۆدەکە لە لای بەرامبەر بخوێنەرەوە',
      'or_choose': 'یان هەڵبژێرە',
      'send_pay_cash': 'ناردن | پارەدان | ڕاكێشانی کاش',
      'send_money_pay': 'ناردنی پارە یان پارەدان',
      'receive_charge_request':
          'وەرگرتن | بارگاویکردنەوەی هەژمارەکەم | داواکاری',
      'charge_wallet_msg': 'بارگاویکردنەوەی پارەی هەژماری جزدانەکەت',
      'splash_safe': 'پارێزراو...',
      'splash_easy': 'ئاسان...',
      'splash_transaction': 'مامەڵە...',
      'splash_payment': 'پارەدان...',
      'acc_copied_msg': 'ژمارەی هەژمارەکە کۆپی کرا بۆ کلیپبۆرد',
      'my_receipt_qr': 'QR ی هەژماری وەسڵەکەم',
      'request': 'داواکاری',
      'back': 'گەڕانەوە',
      'send_pay_cash_upper': 'ناردن | پارەدان | ڕاکێشانی کاش',
      'transfer_send_msg': 'ناردن | گواستنەوەی پارە بۆ rdb | کاش | بانک',
      'history': 'مێژوو',
      'cash_withdrawal': 'ڕاکێشانی کاش',
      'withdrawal_msg': 'ڕاکێشان لە ڕێگەی سەنتەرەکانمان یان بریکارەکانمان',
      'nearby_centers': 'سەنتەرە نزیکەکان',
      'bill_payments': 'پارەدانی پسوولەکان',
      'pay_invoice_msg': 'پارەدانی وەسڵ | پسوولە |',
      'jan': 'کانوونی دووەم',
      'feb': 'شوبات',
      'mar': 'ئازار',
      'apr': 'نیسان',
      'may': 'ئایار',
      'jun': 'حوزەیران',
      'jul': 'تەممووز',
      'aug': 'ئاب',
      'sep': 'ئەیلوول',
      'oct': 'تشرینی یەکەم',
      'nov': 'تشرینی دووەم',
      'dec': 'کانوونی یەکەم',
      'invalid_amount': 'بڕی نادروست',
      'insufficient_balance': 'باڵانسی تەواو نییە',
      'incorrect_account_msg':
          'ژمارەی هەژمارەکە هەڵەیە. دەبێت زیاتر لە ٧ کاراکتەر بێت و - تێدا بێت',
      'account_not_found_msg': 'هەژمارەکە نەدۆزرایەوە',
      'account_lookup_failed_msg': 'پشکنینی هەژمارەکە سەرکەوتوو نەبوو',
      'phone_min_digits_msg': 'ژمارەی تەلەفۆن دەبێت لانی کەم ٧ ژمارە بێت',
      'recipient_account_num': 'ژمارەی هەژماری وەرگر',
      'recipient_phone_num': 'ژمارەی تەلەفۆنی وەرگر',
      'paste': 'لکاندن',
      'office': 'نووسینگە',
      'enter_recipient_acc': 'ژمارەی هەژماری وەرگر داخڵ بکە',
      'enter_recipient_phone': 'ژمارەی تەلەفۆنی وەرگر داخڵ بکە',
      'enter_recipient_name': 'ناوی وەرگر و نازناوی وەرگر بە وردی وەک ناسنامە',
      'enter_recipient_id': 'ژمارەی ناسنامەی وەرگر داخڵ بکە',
      'recipient_name_hint': 'محەمەد ڕەمزی کەتماوی',
      'recipient_id_hint': 'ژمارەی ناسنامە یان پاسپۆرت یان مۆڵەتی شۆفێری',
      'enter': 'داخڵ بکرێت ',
      'or': ' یان    ',
      'edit': 'دەستکاریکردن',
      'sending': 'جاری ناردنە...',
      'send_deposits': 'ناردنی داواکاری داخیڵکردن',
      'expired_code': 'کۆدی بەسەرچوو (کاتی تەواو بوو)',
      'request_cancelled': 'داواکاریەکە هەڵوەشێندرایەوە',
      'request_fulfilled': 'داواکاریەکە پێشتر جێبەجێ کراوە',
      'request_inactive': 'داواکاریەکە چالاک نییە',
      'reference_id': 'سەرچاوە | ناسنامە',
      'minutes_until': ' خولەک تاوەکو ',
      'select_purpose_send': 'هۆکاری ناردنی پارە هەڵبژێرە',
      'select_currency_to_send_msg':
          'پێویستە پێش سکانکردنی کۆد بۆ ناردن، دراوێک هەڵبژێریت',
      'send_label': 'ناردن',
      'receive_label': 'وەرگرتن',
      'until': 'تاوەکو',
      'payment_request_for': 'داواکاری پارەدان بڕی {amount} {currency}',
      'main_sub_account': 'سەرەکی',
      'deposit_type': 'داخیڵکردن',
      'withdrawal_type': 'ڕاکێشان',
      'refund_type': 'گێڕانەوە',
      'order_type': 'داواکاری',
      'invoice_type': 'وەسڵ',

      // KYC
      'kyc_identity_verification': 'پشتڕاستکردنەوەی ناسنامە !',
      'kyc_protect_account': 'هەژمارەکەت بپارێزە و دەستگەیشتنی تەواو بەدەبهێنە',
      'kyc_verify_description':
          'پێویستمانە ناسنامەت یەک جار پشتڕاست بکرێتەوە بۆ پاراستنی هەژمارەکەت لە خەڵەتکاری و پابەندبوون بە ڕێسا ئەمنیەتەکان، پرۆسەیەکی یەک جارانە بۆ دڵنیاکردنەوە لە ناسنامەکەت. یارمەتی دەدات هەژمارەکەت ئیمن بمێنێتەوە، خەڵەتکاری ڕابگرێت، و مامەڵە ئیمنەکان دڵنیا بکات.',
      'kyc_privacy_safe': 'نهێنیەکەت بە تەواوی ئیمنە',
      'kyc_start_verification': 'دەستپێکردنی پشتڕاستکردنەوە',
      'kyc_later_limited': 'دواتر، وەشانی سنوردارەکە بەکاربهێنە',
      'kyc_live_detection_id': 'کەشفی ڕاستەوخۆی ناسنامەکەت',
      'kyc_start_live_detection': 'دەستپێکردنی کەشفی ڕاستەوخۆی ناسنامەکەت',
      'kyc_id_matching_not_correct': 'ناسنامەکە لەگەڵ وێنەکەت دەگونجێت نییە',
      'kyc_id_discrepancy':
          'جیاوازییەکمان تێبینی کرد لە وێنەکەدا و هەروەها گومانیش هەیە لەسەر ناسنامەی کەسیەکە.',
      'kyc_try_again_correction': 'دووبارە هەوڵ بدە لەگەڵ سەرستکردنەوە',
      'kyc_rematch': 'دووبارە تەقنەکردن',
      'kyc_live_face_detection': 'کەشفی ڕووخساری ڕاستەوخۆ',
      'kyc_face_centered':
          'تکایە ڕووخسارەکەت لە ناوەندی ئەکرانەکەدا بهێڵەوە و ڕووبەرووی پێشەوە بێت',
      'kyc_live_id_done': 'کەشفی ڕاستەوخۆی ناسنامە تەواو بوو',
      'kyc_information_detected': 'زانیارییەکانی کەشفکراو',
      'kyc_id_type': 'جۆری ناسنامە',
      'kyc_country': 'وڵات',
      'kyc_name': 'ناو',
      'kyc_national_number': 'ژمارەی نیشتیمانی',
      'kyc_birthday': 'بەرواری لەدایکبوون',
      'kyc_correct_next': 'دروستە، دواتر',
      'kyc_contact_you_soon': 'بەزوویی پەیوەندیت پێوە دەکەین',
      'kyc_incorrect_try_again': 'هەڵەیە، دووبارە هەوڵ بدە',
      'kyc_success_verification': 'پشتڕاستکردنەوە سەرکەوتوو بوو !',
      'kyc_full_access':
          'ئێستا دەتوانیت تەواو سود لە دەستگەیشتنی تەواو وەربگریت',
      'kyc_video_call_from_our_side': 'ویدیۆ کۆلێج لە لایمانەوە',
      'kyc_ai_call_description':
          'کۆلێجی زیرەکی دەستکرد بۆ ١٥ چرکە، بە تەواوی نهێنی بۆ دڵنیاکردنەوە لە ئیمنی هەژمارەکەت',
      'kyc_start_video_call': 'دەستپێکردنی ویدیۆ کۆلێج',
      'kyc_later': 'دواتر',
      'kyc_end_video_call': 'کۆتایی ویدیۆ کۆلێج',
      'kyc_front_side': 'لای پێشەوە ',
      'kyc_back_side': 'لای دواوە ',
      'kyc_verify_identity_btn': 'پشتڕاستکردنەوەی ناسنامە',
      'kyc_low_light_warning': 'ڕووناکی کەم! تکایە ڕووناکی باشتر بکە',
      'kyc_align_id': 'ناسنامەکەت لەناو چوارچێوەکەدا راست بکەرەوە',
      'kyc_camera_error': 'کامێرا بەردەست نییە. مۆڵەتەکان بپشکنە.',
      'kyc_flip_to_back':
          'ناسنامەکە بگەڕێنەوە — لای دواوە لەناو چوارچێوەکەدا راست بکەرەوە',
      'kyc_too_far': 'بەلگەنامەکە بنێرە نزیکتر بۆ کامێرا',
      'kyc_too_close': 'بەلگەنامەکە کەمێک دوورتر بکەرەوە لە کامێرا',
      'kyc_liveness_turn_left': 'ڕووخسارەکەت بۆ چەپ بجوڵێنە',
      'kyc_liveness_turn_right': 'ڕووخسارەکەت بۆ ڕاست بجوڵێنە',
      'kyc_liveness_look_up': 'ڕووخسارەکەت کەمێک بەرز بکەرەوە',
      'kyc_liveness_blink': 'تکایە هەر دوو چاوەکەت دابخە',
      'kyc_align_face': 'ڕووخسارەکەت لە ناو چوارچێوەکەدا دابنێ',
      'kyc_liveness_verifying': 'پشکنینی زیندوویی دەکرێت...',
      'kyc_liveness_done': 'زیندوویی بە سەرکەوتوویی پشتڕاست کرایەوە',
      'kyc_liveness_failed':
          'پشکنینی زیندوویی سەرکەوتوو نەبوو. دووبارە هەوڵ بدە.',
      'kyc_camera_auto_closed':
          'کامێرا دوای 30 چرکە بێ چالاکی بە خۆکارانە داخرا',
      'kyc_reopen_camera': 'کردنەوەی کامێرا',
      'no_internet_title': 'هیچ پەیوەندییەکی ئینتەرنێت نییە',
      'no_internet_subtitle':
          'تکایە پەیوەندی ئینتەرنێتەکەت بپشکنە و دڵنیابە کە بە Wi-Fi یان داتای مۆبایل پەیوەندیت هەیە.',
    },
    'tr': {
      // Home Tab
      'home_title': 'Anasayfa',
      'total_balance': 'Toplam Bakiyeniz',
      'add_currency': 'Para Birimi Ekle',
      'all_transactions': 'Tüm İşlemler',
      'balance': 'Bakiye',
      'your_total_balance': 'Toplam Bakiyeniz',
      'available_balance': 'Mevcut Bakiye',
      'records': 'Kayıtlar',
      'transactions': 'Islemler',
      'no_deposit_requests_yet': 'Henüz hiçbir yatırma talebi yok',
      'transaction_history': 'İşlem Geçmişi',
      'no_transactions': 'Henüz hiçbir işlem yok',
      'chart': 'Grafik',
      'recent_transactions': 'Son İşlemler',
      'view_all': 'Tümünü Görüntüle',
      'your_total_balance_of': 'Toplam {currency} Bakiyeniz',
      'add_account_of': '{currency} Hesabı Ekle',

      // Wallet Tab
      'my_wallet': 'Cüzdanım',
      'manage_balances': 'Bakiyelerinizi ve işlemlerinizi yönetin',
      'actions_for': 'İçin İşlemler',
      'add_funds': 'Para Ekle (Yatırma)',
      'deposit': 'Yatırma',
      'balance_available': 'Mevcut Bakiye',
      'no_currencies': 'Kullanılabilir para birimi yok',
      'deposit_requests': 'Yatırma Talepleri',
      'status': 'Durum',
      'amount': 'Tutar',
      'date': 'Tarih',
      'pending': 'Beklemede',
      'completed': 'Tamamlandı',
      'failed': 'Başarısız',
      'withdrawal': 'Para Çekme',
      'refund': 'İade',
      'order': 'Sipariş',
      'invoice': 'Fatura',
      'id': 'ID',
      'bank': 'Banka',
      'fees': 'Ücretler',
      'tax': 'Vergi',
      'approved': 'Onaylandı',
      'reference': 'Referans | ID',

      // Addresses Tab
      'addresses': 'Adresler',
      'my_addresses': 'Adreslerim',
      'add_address': 'Adres Ekle',
      'copy': 'Kopyala',
      'copied': 'Kopyalandı',
      'no_addresses': 'Henüz hiçbir adres yok',

      // Settings Tab
      'settings': 'Ayarlar',
      'language': 'Dil',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'Dili Seçin',
      'about': 'Hakkında',
      'about_us': 'Hakkımızda',
      'terms_conditions': 'Şartlar ve Koşullar',
      'legal_information': 'Yasal Bilgiler',
      'share_app': 'Uygulamayı Paylaş',
      'version': 'Sürüm',
      'logout': 'Çıkış Yap',
      'personal_information': 'Kişisel Bilgiler',
      'account_information': 'Hesap Bilgileri',
      'email': 'E-posta',
      'phone_number': 'Telefon Numarası',
      'first_name': 'Ad',
      'last_name': 'Soyad',
      'account_status': 'Hesap Durumu',
      'two_factor_authentication': 'İki Faktörlü Doğrulama',
      'member_since': 'Üyelik Tarihi',
      'verified': 'Doğrulandı',
      'not_provided': 'Belirtilmedi',
      'active': 'Aktif',
      'disabled': 'Devre Dışı',
      'enabled': 'Etkin',
      'registered': 'Kayıtlı',
      'unprotected_account_limited_access': 'Korunmayan Hesap | Sınırlı Erişim',
      'weekly_transfer_volume': 'HAFTALIK TRANSFER HACMİ',
      'usd_renew': 'USD | YENİLE',
      'fri_1010': 'CUMA 10:10',
      'protect_account_full_access': 'Hesabınızı Koruyun | Tam Erişim',
      'secure_account_safe_transactions':
          'HESABINIZI GÜVENDE TUTUN, GÜVENLİ İŞLEMLER SAĞLAYIN',
      'protect_verify_now': 'Şimdi Koru ve Doğrula',
      'id_label': 'Kimlik',
      'add_photo': 'Fotoğraf Ekle',
      'active_session': 'Aktif Oturum',
      'profile_photo': 'Profil Fotoğrafı',
      'add_profile_photo': 'Profil Fotoğrafı Ekle',
      'edit_profile_photo': 'Profil Fotoğrafını Düzenle',
      'choose': 'Seç',
      'take_photo': 'Fotoğraf Çek',
      'remove': 'Kaldır',
      'save': 'Kaydet',
      'no_photos': 'Mevcut fotoğraf yok',
      'permission_camera_required': 'Fotoğraf çekmek için kamera izni gerekli.',
      'permission_gallery_required':
          'Fotoğraf seçmek için galeri izni gerekli.',
      'camera_unavailable': 'Kamera kullanılamıyor',
      'preview_crop': 'Önizleme ve Kırp',
      'crop': 'Kırp',
      'use_photo': 'Fotoğrafı Kullan',

      // Request Flow
      'payment_request': 'Ödeme Talebi',
      'generate_request': 'Talep Oluştur',
      'requesting': 'Talep ediliyor...',
      'valid_until': 'Geçerlilik Süresi',
      'note': 'Not',
      'select_purpose_request': 'Para Talep Amacını Seçin',
      'cannot_use_after_expiry':
          'Süresi dolduktan sonra kod kullanılamayacaktır',
      'purpose_of_request': 'Para Talep Amacı',
      'always': 'Her zaman',
      'minute_1': '1 Dakika',
      'minutes_3': '3 Dakika',
      'minutes_15': '15 Dakika',
      'hour_1': '1 Saat',
      'hours_24': '24 Saat',
      'work_partnership': 'İş / Ortaklık',
      'service_fees': 'Hizmet Ücretleri',
      'home_rent': 'Ev Kirası',
      'office_shop_rent': 'Ofis / Dükkan Kirası',
      'deposit_request': 'Para Yatırma Talebi',
      'enter_amount': 'Tutarı Girin',
      'enter_reference': 'Referans | ID Girin',
      'enter_note_receiver': 'Alıcı hesabında görünecek notu girin',

      // Send Flow
      'transfer_send': 'Transfer | Gönder',
      'sender_account': 'Gönderen Hesabı',
      'send_to': 'Şuna Gönder',
      'recipient_account': 'Alıcı Hesabı',
      'recipient_phone': 'Alıcı Telefon Numarası',
      'enter_account_or_phone': 'Hesap veya Telefon Numarası Girin',
      'recipient_name_id': 'Alıcı Adı | ID',
      'recipient_id_num': 'Alıcı ID Numarası',
      'amount_to_be_sent': 'Gönderilecek Tutar',
      'purpose_of_send': 'Gönderim Amacı',
      'money_sent_success': 'Para başarıyla gönderildi',
      'transaction_failed': 'İşlem başarısız oldu',
      'receipt': 'Makbuz',

      // Common
      'loading': 'Yükleniyor...',
      'error': 'Hata',
      'retry': 'Yeniden Dene',
      'kyc_rescan': 'Yeniden Tara',
      'ok': 'Tamam',
      'safe': 'Güvenli',
      'powered_by': 'Tarafından Destekleniyor',
      'failed_to_load': 'Yükleme Başarısız',
      'try_again': 'Tekrar Deneyin',
      'success': 'Başarılı',
      'source_bank': 'Kaynak Banka',
      'select_bank': 'Bir banka seçin...',
      'load_more': 'Daha fazla yükle',
      'amount_label': 'Miktar',
      'complete_form_deposit': 'Para yatırma talebi için formu doldurun.',
      'deposit_symbol': 'Para Yatırma',
      'fee_label': 'Ücret:',
      'tax_label': 'Vergi:',
      'you_receive': 'Alacağınız Tutar:',
      'proof_of_transfer': 'Transfer Kanıtı',
      'click_to_upload': 'Resim yüklemek için tıklayın',
      'upload_success_msg': 'Yükleme başarılı',
      'change_image': 'Resmi değiştir',
      'uploading_msg': 'Yükleniyor...',
      'confirm_upload': 'Yüklemeyi onayla',
      'confirm_deposit_label': 'Para Yatırmayı Onayla',
      'deposit_request_submitted': 'Yatırma talebi başarıyla iletildi',
      'deposit_completed_success': 'Yatırma başarıyla tamamlandı',
      'failed_to_submit_deposit': 'Yatırma talebi iletilemedi',
      'failed_to_load_banks': 'Bankalar yüklenemedi',
      'page': 'Sayfa',
      'of': '/',
      'done': 'Tamam',
      'copy_clipboard': 'Panoya kopyalandı',
      'failed_to_save': 'Kaydedilemedi',
      'saved_successfully': 'Başarıyla kaydedildi',
      'download': 'İndir',
      'share': 'Paylaş',
      'account_name': 'Hesap Adı',
      'account_number': 'Hesap Numarası',
      'date_time': 'Tarih ve Saat',
      'type': 'Tür',
      'succeeded': 'Başarılı',
      'american_dollars': 'Amerikan Doları',
      'receipt_footer_msg':
          'Parayı tüm merkezlerimizde alabilir veya uygulamamızı indirip hesap açarak parayı kullanabilir ve tüm hizmetlerden yararlarbilirsiniz.',
      'statistic': 'İstatistik',
      'info': 'Bilgi',
      'scan_qr_msg': 'Harekete geçmek için karşı taraftaki kodu okuyun',
      'or_choose': 'Veya Seçin',
      'send_pay_cash': 'Gönder | Öde | Nakit Çekme',
      'send_money_pay': 'Para Gönder veya Öde',
      'receive_charge_request': 'Al | Hesabımı Yükle | İstek',
      'charge_wallet_msg': 'Cüzdan hesabınıza para yükleyin',
      'splash_safe': 'güvenli...',
      'splash_easy': 'kolay...',
      'splash_transaction': 'işlem...',
      'splash_payment': 'ödeme...',
      'acc_copied_msg': 'Hesap numarası panoya kopyalandı',
      'my_receipt_qr': 'Makbuz Hesabım QR',
      'request': 'İstek',
      'back': 'Geri',
      'send_pay_cash_upper': 'GÖNDER | ÖDE | NAKİT ÇEKME',
      'transfer_send_msg': 'Gönder | rdb | nakit | bankaya para transferi yap',
      'history': 'Geçmiş',
      'cash_withdrawal': 'Nakit Çekme',
      'withdrawal_msg':
          'Merkezlerimiz veya Acentelerimiz Aracılığıyla Para Çekme',
      'nearby_centers': 'Yakındaki Merkezler',
      'bill_payments': 'Fatura Ödemeleri',
      'pay_invoice_msg': 'Fatura Öde | Makbuz |',
      'jan': 'Ocak',
      'feb': 'Şubat',
      'mar': 'Mart',
      'apr': 'Nisan',
      'may': 'Mayıs',
      'jun': 'Haziran',
      'jul': 'Temmuz',
      'aug': 'Ağustos',
      'sep': 'Eylül',
      'oct': 'Ekim',
      'nov': 'Kasım',
      'dec': 'Aralık',
      'invalid_amount': 'Geçersiz Tutar',
      'insufficient_balance': 'Yetersiz Bakiye',
      'incorrect_account_msg':
          'Hatalı hesap numarası. 7 karakterden uzun olmalı ve - içermelidir',
      'account_not_found_msg': 'Hesap bulunamadı',
      'account_lookup_failed_msg': 'Hesap doğrulanamadı',
      'phone_min_digits_msg': 'Telefon numarası en az 7 haneli olmalıdır',
      'recipient_account_num': 'Alıcı Hesap Numarası',
      'recipient_phone_num': 'Alıcı Telefon Numarası',
      'paste': 'Yapıştır',
      'office': 'Ofis',
      'enter_recipient_acc': 'Alıcı Hesap Numarasını Girin',
      'enter_recipient_phone': 'Alıcı Telefon Numarasını Girin',
      'enter_recipient_name': 'Alıcı Adı ve Soyadını Kimlikteki Gibi Tam Girin',
      'enter_recipient_id': 'Alıcı Kimlik Numarasını Girin',
      'recipient_name_hint': 'Mohamad Ramzi Katmawi',
      'recipient_id_hint': 'Kimlik Kartı veya Pasaport veya Ehliyet Numarası',
      'enter': 'Girin ',
      'or': ' Veya    ',
      'edit': 'Düzenle',
      'sending': 'Gönderiliyor...',
      'send_deposits': 'Emanetleri Gönder',
      'expired_code': 'Süresi Dolmuş Kod (Zaman Doldu)',
      'request_cancelled': 'Talep İptal Edildi',
      'request_fulfilled': 'Talep Zaten Karşılandı',
      'request_inactive': 'Talep Aktif Değil',
      'reference_id': 'Referans | ID',
      'minutes_until': ' Dakika Kaldı ',
      'select_purpose_send': 'Para Gönderim Amacını Seçin',
      'select_currency_to_send_msg':
          'Göndermek için barkodu taramadan önce bir para birimi seçin',
      'send_label': 'Gönder',
      'receive_label': 'Al',
      'until': 'kadar',
      'payment_request_for': '{amount} {currency} için ödeme talebi',
      'main_sub_account': 'Ana',
      'deposit_type': 'Yatırma',
      'withdrawal_type': 'Çekme',
      'refund_type': 'İade',
      'order_type': 'Sipariş',
      'invoice_type': 'Fatura',

      // KYC
      'kyc_identity_verification': 'Kimlik Doğrulama !',
      'kyc_protect_account': 'Hesabınızı Koruyun ve Tam Erişim Kazanın',
      'kyc_verify_description':
          'Hesabınızı dolandırıcılıktan korumak ve güvenlik düzenlemelerine uymak için kimliğinizi yalnızca bir kez doğrulamamız gerekiyor. Bu, kimliğinizi onaylamak için tek seferlik bir işlemdir. Hesabınızın güvende kalmasına, dolandırıcılığın önlenmesine ve güvenli işlemler yapılmasına yardımcı olur.',
      'kyc_privacy_safe': 'Gizliliğiniz Tamamen Güvende',
      'kyc_start_verification': 'Doğrulamayı Başlat',
      'kyc_later_limited': 'Daha Sonra, Sınırlı Sürümü Kullan',
      'kyc_live_detection_id': 'Kimliğinizi Canlı Tespit Et',
      'kyc_start_live_detection': 'Kimliğinizi Canlı Tespiti Başlat',
      'kyc_id_matching_not_correct': 'Kimlik Fotoğrafınızla Eşleşmiyor',
      'kyc_id_discrepancy':
          'Görüntüde Bir Tutarsızlık Fark Ettik Ve Kişisel Kimlik Konusunda Da Şüphe Var.',
      'kyc_try_again_correction': 'Düzeltmeyle Tekrar Deneyin',
      'kyc_rematch': 'Yeniden Eşleştir',
      'kyc_live_face_detection': 'Canlı Yüz Tespiti',
      'kyc_face_centered':
          'Lütfen Yüzünüzü Ekranın Ortasında Tutun ve Öne Bakın',
      'kyc_live_id_done': 'Canlı Kimlik Tespiti Tamamlandı',
      'kyc_information_detected': 'Tespit Edilen Bilgiler',
      'kyc_id_type': 'Kimlik Türü',
      'kyc_country': 'Ülke',
      'kyc_name': 'Ad',
      'kyc_national_number': 'Ulusal Numara',
      'kyc_birthday': 'Doğum Tarihi',
      'kyc_correct_next': 'Doğru, İleri',
      'kyc_contact_you_soon': 'Yakında Sizinle İletişime Geçeceğiz',
      'kyc_incorrect_try_again': 'Yanlış, Tekrar Dene',
      'kyc_success_verification': 'Doğrulama Başarılı !',
      'kyc_full_access': 'Tam Erişimin Keyfini Çıkarabilirsiniz',
      'kyc_video_call_from_our_side': 'Bizim Tarafımızdan Video Görüşme',
      'kyc_ai_call_description':
          '15 Saniyelik Yapay Zeka Görüşmesi, Hesabınızın Güvenliğini Sağlamak İçin Tamamen Şifrelenmiş',
      'kyc_start_video_call': 'Video Görüşmeyi Başlat',
      'kyc_later': 'Daha Sonra',
      'kyc_end_video_call': 'Video Görüşmeyi Bitir',
      'kyc_front_side': 'Ön Yüz ',
      'kyc_back_side': 'Arka Yüz ',
      'kyc_verify_identity_btn': 'Kimliği Doğrula',
      'kyc_low_light_warning':
          'Işık yetersiz! Devam etmek için aydınlatmayı iyileştirin',
      'kyc_align_id': 'Kimlik kartınızı çerçeve içine hizalayın',
      'kyc_camera_error': 'Kamera kullanılamıyor. İzinleri kontrol edin.',
      'kyc_flip_to_back': 'Kimliği çevirin — arka yüzü çerçeve içine hizalayın',
      'kyc_too_far': 'Belgeyi kameraya daha yakın tutun',
      'kyc_too_close': 'Belgeyi kameradan biraz uzaklaştırın',
      'kyc_liveness_turn_left': 'Yüzünüzü sola çevirin',
      'kyc_liveness_turn_right': 'Yüzünüzü sağa çevirin',
      'kyc_liveness_look_up': 'Yüzünüzü biraz yukarı kaldırın',
      'kyc_liveness_blink': 'Lütfen her iki gözünüzü kırpın',
      'kyc_align_face': 'Yüzünüzü çerçeveye yerleştirin',
      'kyc_liveness_verifying': 'Canlılık doğrulanıyor...',
      'kyc_liveness_done': 'Canlılık başarıyla doğrulandı',
      'kyc_liveness_failed':
          'Canlılık doğrulaması başarısız. Lütfen tekrar deneyin.',
      'kyc_camera_auto_closed':
          '30 saniye işlem olmadığı için kamera otomatik kapatıldı',
      'kyc_reopen_camera': 'Kamerayı Yeniden Aç',
      'no_internet_title': 'İnternet Bağlantısı Yok',
      'no_internet_subtitle':
          'Lütfen internet bağlantınızı kontrol edin ve Wi-Fi veya mobil veriye bağlı olduğunuzdan emin olun.',
    },
  };

  /// Get localized string for the given key in the specified language
  static String get(String languageCode, String key) {
    final lang = _strings[languageCode];
    if (lang == null) {
      return _strings['en']![key] ?? key;
    }
    return lang[key] ?? _strings['en']![key] ?? key;
  }

  /// All supported languages
  static const List<String> supportedLanguages = ['en', 'ar', 'ku', 'tr'];
}
