/// Localized strings for the wallet app
/// Supports: English (en), Arabic (ar), Kurdish (ku), Turkish (tr)
class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      // Home Tab
      'home_title': 'Home',
      'total_balance': 'Your Total Balance',
      'add_currency': 'Add Currency',
      'your_total_balance': 'Your Total Balance',
      'records': 'Records',
      'no_deposit_requests_yet': 'No deposit requests yet',
      'available_balance': 'Available Balance',
      'all_transactions': 'All Transactions',
      'balance': 'Balance',
      'transaction_history': 'Transaction History',
      'no_transactions': 'No transactions yet',
      'recent_transactions': 'Recent Transactions',
      'view_all': 'View All',

      // Wallet Tab
      'my_wallet': 'My Wallet',
      'manage_balances': 'Manage your balances and transactions',
      'actions_for': 'Actions for',
      'add_funds': 'Add Funds (Deposit)',
      'deposit': 'Deposit',
      'balance_available': 'Available Balance',
      'no_currencies': 'No currencies available',
      'deposit_requests': 'Deposit Requests',
      'status': 'Status',
      'amount': 'Amount',
      'date': 'Date',
      'pending': 'Pending',
      'completed': 'Completed',
      'failed': 'Failed',
      'withdrawal': 'Withdrawal',
      'refund': 'Refund',
      'order': 'Order',
      'invoice': 'Invoice',
      'id': 'ID',
      'bank': 'Bank',
      'fees': 'Fees',
      'tax': 'Tax',

      // Addresses Tab
      'addresses': 'Addresses',
      'my_addresses': 'My Addresses',
      'add_address': 'Add Address',
      'copy': 'Copy',
      'copied': 'Copied',
      'no_addresses': 'No addresses yet',

      // Settings Tab
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'Select Language',
      'about': 'About',
      'version': 'Version',
      'logout': 'Logout',

      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'ok': 'OK',
      'safe': 'Safe',
      'powered_by': 'Powered By',
      'failed_to_load': 'Failed to load',
      'try_again': 'Try again',
      'success': 'Success',
      'source_bank': 'Source Bank',
      'select_bank': 'Select a bank...',
      'load_more': 'Load more',
      'amount_label': 'Amount',
      'complete_form_deposit': 'Complete the form to request a deposit.',
      'deposit_symbol': 'Deposit',
      'fee_label': 'Fee:',
      'tax_label': 'Tax:',
      'you_receive': 'You Receive:',
      'proof_of_transfer': 'Proof of Transfer',
      'click_to_upload': 'Click to upload image',
      'upload_success_msg': 'Upload successful',
      'change_image': 'Change image',
      'uploading_msg': 'Uploading...',
      'confirm_upload': 'Confirm upload',
      'confirm_deposit_label': 'Confirm Deposit',
      'deposit_request_submitted': 'Deposit request submitted successfully',
      'deposit_completed_success': 'Deposit completed successfully',
      'failed_to_submit_deposit': 'Failed to submit deposit request',
      'failed_to_load_banks': 'Failed to load banks',
      'page': 'Page',
      'of': 'of',
    },
    'ar': {
      // Home Tab
      'home_title': 'الرئيسية',
      'total_balance': 'إجمالي رصيدك',
      'add_currency': 'إضافة عملة',
      'available_balance': 'الرصيد المتاح',
      'records': 'السجلات',
      'no_deposit_requests_yet': 'لا توجد طلبات إيداع حتى الآن',
      'all_transactions': 'جميع المعاملات',
      'your_total_balance': 'إجمالي رصيدك',
      'balance': 'الرصيد',
      'transaction_history': 'سجل المعاملات',
      'no_transactions': 'لا توجد معاملات حتى الآن',
      'recent_transactions': 'المعاملات الأخيرة',
      'view_all': 'عرض الكل',

      // Wallet Tab
      'my_wallet': 'محفظتي',
      'manage_balances': 'إدارة أرصدتك والمعاملات',
      'actions_for': 'الإجراءات لـ',
      'add_funds': 'إضافة أموال (إيداع)',
      'deposit': 'إيداع',
      'balance_available': 'الرصيد المتاح',
      'no_currencies': 'لا توجد عملات متاحة',
      'deposit_requests': 'طلبات الإيداع',
      'status': 'الحالة',
      'amount': 'المبلغ',
      'date': 'التاريخ',
      'pending': 'قيد الانتظار',
      'completed': 'مكتمل',
      'failed': 'فشل',
      'withdrawal': 'سحب',
      'refund': 'استرداد',
      'order': 'طلب',
      'invoice': 'فاتورة',
      'id': 'المعرف',
      'bank': 'البنك',
      'fees': 'الرسوم',
      'tax': 'الضريبة',

      // Addresses Tab
      'addresses': 'العناوين',
      'my_addresses': 'عناويني',
      'add_address': 'إضافة عنوان',
      'copy': 'نسخ',
      'copied': 'تم النسخ',
      'no_addresses': 'لا توجد عناوين حتى الآن',

      // Settings Tab
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'اختر اللغة',
      'about': 'حول',
      'version': 'الإصدار',
      'logout': 'تسجيل الخروج',

      // Common
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'retry': 'إعادة محاولة',
      'cancel': 'إلغاء',
      'ok': 'حسناً',
      'safe': 'آمن',
      'powered_by': 'مدعوم من',
      'failed_to_load': 'فشل التحميل',
      'try_again': 'حاول مرة أخرى',
      'success': 'نجح',
      'source_bank': 'البنك المصدر',
      'select_bank': 'اختر بنكاً...',
      'load_more': 'تحميل المزيد',
      'amount_label': 'المبلغ',
      'complete_form_deposit': 'أكمل النموذج لطلب الإيداع.',
      'deposit_symbol': 'إيداع',
      'fee_label': 'الرسوم:',
      'tax_label': 'الضريبة:',
      'you_receive': 'ستستلم:',
      'proof_of_transfer': 'إثبات الحوالة',
      'click_to_upload': 'اضغط لرفع صورة',
      'upload_success_msg': 'تم الرفع بنجاح',
      'change_image': 'تغيير الصورة',
      'uploading_msg': 'جاري الرفع...',
      'confirm_upload': 'تأكيد الرفع',
      'confirm_deposit_label': 'تأكيد الإيداع',
      'deposit_request_submitted': 'تم تقديم طلب الإيداع بنجاح',
      'deposit_completed_success': 'تم اكتمال الإيداع بنجاح',
      'failed_to_submit_deposit': 'فشل في تقديم طلب الإيداع',
      'failed_to_load_banks': 'فشل في تحميل البنوك',
      'page': 'صفحة',
      'of': 'من',
    },
    'ku': {
      // Home Tab
      'home_title': 'سەرەتا',
      'total_balance': 'کۆی بەروونی تۆ',
      'add_currency': 'موژدە سازی زیادکە',
      'all_transactions': 'هەموو وەرگێڕانەکان',
      'available_balance': 'بەروونی دەستدەست',
      'records': 'تۆمارەکان',
      'no_deposit_requests_yet': 'هێشتا هیچ داواکاری داخواڵێک نیە',
      'balance': 'بەروونی',
      'transaction_history': 'مێژووی وەرگێڕانەکان',
      'no_transactions': 'هیچ وەرگێڕانەی تێدا نیە',
      'recent_transactions': 'وەرگێڕانە نوێیەکان',
      'your_total_balance': 'کۆی بەروونی تۆ',
      'view_all': 'هەمووی ببینە',

      // Wallet Tab
      'my_wallet': 'کیسەی من',
      'manage_balances': 'بەڕێوەبردنی بەروونی و وەرگێڕانەکان',
      'actions_for': 'کردارەکان بۆ',
      'add_funds': 'زیادکردنی پارە (داخواڵ)',
      'deposit': 'داخواڵ',
      'balance_available': 'بەروونی دەستدەست',
      'no_currencies': 'موژدە سازێی بەردەست نیە',
      'deposit_requests': 'داواکاری داخواڵ',
      'status': 'دۆخ',
      'amount': 'بەرھەم',
      'date': 'بەرواری',
      'pending': 'چاوەڕۆیان کردن',
      'completed': 'تێچوو',
      'failed': 'شکست',
      'withdrawal': 'ڕاکێشان',
      'refund': 'گێڕانەوە',
      'order': 'داواکاری',
      'invoice': 'وەسڵ',
      'id': 'ناسنامە',
      'bank': 'بانک',
      'fees': 'ڕسوومات',
      'tax': 'باج',

      // Addresses Tab
      'addresses': 'ناونیشانەکان',
      'my_addresses': 'ناونیشانەکانی من',
      'add_address': 'زیادکردنی ناونیشان',
      'copy': 'کۆپی',
      'copied': 'کۆپی کرا',
      'no_addresses': 'هیچ ناونیشانی تێدا نیە',

      // Settings Tab
      'settings': 'ڕێکخستنەکان',
      'language': 'زمان',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'زمانی هەڵبژێرە',
      'about': 'دەربارەی',
      'version': 'وەشان',
      'logout': 'دەرچوون',

      // Common
      'loading': 'بارکردن...',
      'error': 'هەڵە',
      'retry': 'هەوڵ دووبارە',
      'cancel': 'پاشگەزبوونەوە',
      'ok': 'باشە',
      'safe': 'ئیمن',
      'powered_by': 'پشتگیری',
      'failed_to_load': 'بارکردن شکست',
      'try_again': 'دووبارە هەوڵ بدە',
      'success': 'سەرکەوتوو',
      'source_bank': 'بانکی سەرچاوە',
      'select_bank': 'بانکێ هەڵبژێرە...',
      'load_more': 'زیاتر بەرزبکەرەوە',
      'amount_label': 'بڕی',
      'complete_form_deposit': 'تکایە فۆرمەکە پڕبکەرەوە بۆ داواکاری داخیڵکردن.',
      'deposit_symbol': 'داخیڵکردن',
      'fee_label': 'ڕسوومات:',
      'tax_label': 'باج:',
      'you_receive': 'تۆ وەردەگریت:',
      'proof_of_transfer': 'بەڵگەی گواستنەوە',
      'click_to_upload': 'کلیک بکە بۆ بەرزکردنەوەی وێنە',
      'upload_success_msg': 'بەرزکردنەوە سەرکەوتوو بوو',
      'change_image': 'وێنەکە بگۆڕە',
      'uploading_msg': 'جاری بەرزکردنەوەیە...',
      'confirm_upload': 'بەرزکردنەوە پشتڕاست بکەرەوە',
      'confirm_deposit_label': 'داخیڵکردن پشتڕاست بکەرەوە',
      'deposit_request_submitted': 'داواکاری داخیڵکردن بە سەرکەوتوویی نێردرا',
      'deposit_completed_success': 'داخیڵکردن بە سەرکەوتوویی تەواو بوو',
      'failed_to_submit_deposit': 'ناردنی داواکاری داخیڵکردن شکستی هێنا',
      'failed_to_load_banks': 'بارکردنی بانکەکان شکستی هێنا',
      'page': 'لاپەڕە',
      'of': 'لە',
    },
    'tr': {
      // Home Tab
      'home_title': 'Anasayfa',
      'total_balance': 'Toplam Bakiyeniz',
      'add_currency': 'Para Birimi Ekle',
      'all_transactions': 'Tüm İşlemler',
      'balance': 'Bakiye',
      'your_total_balance': 'Toplam Bakiyeniz',
      'available_balance': 'Mevcut Bakiye',
      'records': 'Kayıtlar',
      'no_deposit_requests_yet': 'Henüz hiçbir yatırma talebi yok',
      'transaction_history': 'İşlem Geçmişi',
      'no_transactions': 'Henüz hiçbir işlem yok',
      'recent_transactions': 'Son İşlemler',
      'view_all': 'Tümünü Görüntüle',

      // Wallet Tab
      'my_wallet': 'Cüzdanım',
      'manage_balances': 'Bakiyelerinizi ve işlemlerinizi yönetin',
      'actions_for': 'İçin İşlemler',
      'add_funds': 'Para Ekle (Yatırma)',
      'deposit': 'Yatırma',
      'balance_available': 'Mevcut Bakiye',
      'no_currencies': 'Kullanılabilir para birimi yok',
      'deposit_requests': 'Yatırma Talepleri',
      'status': 'Durum',
      'amount': 'Tutar',
      'date': 'Tarih',
      'pending': 'Beklemede',
      'completed': 'Tamamlandı',
      'failed': 'Başarısız',
      'withdrawal': 'Para Çekme',
      'refund': 'İade',
      'order': 'Sipariş',
      'invoice': 'Fatura',
      'id': 'ID',
      'bank': 'Banka',
      'fees': 'Ücretler',
      'tax': 'Vergi',

      // Addresses Tab
      'addresses': 'Adresler',
      'my_addresses': 'Adreslerim',
      'add_address': 'Adres Ekle',
      'copy': 'Kopyala',
      'copied': 'Kopyalandı',
      'no_addresses': 'Henüz hiçbir adres yok',

      // Settings Tab
      'settings': 'Ayarlar',
      'language': 'Dil',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'Dili Seçin',
      'about': 'Hakkında',
      'version': 'Sürüm',
      'logout': 'Çıkış Yap',

      // Common
      'loading': 'Yükleniyor...',
      'error': 'Hata',
      'retry': 'Yeniden Dene',
      'cancel': 'İptal',
      'ok': 'Tamam',
      'safe': 'Güvenli',
      'powered_by': 'Tarafından Destekleniyor',
      'failed_to_load': 'Yükleme Başarısız',
      'try_again': 'Tekrar Deneyin',
      'success': 'Başarılı',
      'source_bank': 'Kaynak Banka',
      'select_bank': 'Bir banka seçin...',
      'load_more': 'Daha fazla yükle',
      'amount_label': 'Miktar',
      'complete_form_deposit': 'Para yatırma talebi için formu doldurun.',
      'deposit_symbol': 'Para Yatırma',
      'fee_label': 'Ücret:',
      'tax_label': 'Vergi:',
      'you_receive': 'Alacağınız Tutar:',
      'proof_of_transfer': 'Transfer Kanıtı',
      'click_to_upload': 'Resim yüklemek için tıklayın',
      'upload_success_msg': 'Yükleme başarılı',
      'change_image': 'Resmi değiştir',
      'uploading_msg': 'Yükleniyor...',
      'confirm_upload': 'Yüklemeyi onayla',
      'confirm_deposit_label': 'Para Yatırmayı Onayla',
      'deposit_request_submitted': 'Yatırma talebi başarıyla iletildi',
      'deposit_completed_success': 'Yatırma başarıyla tamamlandı',
      'failed_to_submit_deposit': 'Yatırma talebi iletilemedi',
      'failed_to_load_banks': 'Bankalar yüklenemedi',
      'page': 'Sayfa',
      'of': '/',
    },
  };

  /// Get localized string for the given key in the specified language
  static String get(String languageCode, String key) {
    final lang = _strings[languageCode];
    if (lang == null) {
      return _strings['en']![key] ?? key;
    }
    return lang[key] ?? _strings['en']![key] ?? key;
  }

  /// All supported languages
  static const List<String> supportedLanguages = ['en', 'ar', 'ku', 'tr'];
}
