/// Localized strings for the wallet app
/// Supports: English (en), Arabic (ar), Kurdish (ku), Turkish (tr)
class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      // Home Tab
      'home_title': 'Home',
      'total_balance': 'Your Total Balance',
      'add_currency': 'Add Currency',
      'your_total_balance': 'Your Total Balance',
      'records': 'Records',
      'no_deposit_requests_yet': 'No deposit requests yet',
      'available_balance': 'Available Balance',
      'all_transactions': 'All Transactions',
      'balance': 'Balance',
      'transaction_history': 'Transaction History',
      'no_transactions': 'No transactions yet',
      'recent_transactions': 'Recent Transactions',
      'view_all': 'View All',
      'your_total_balance_of': 'Your Total {currency} Balance',
      'add_account_of': 'Add {currency} Account',

      // Wallet Tab
      'my_wallet': 'My Wallet',
      'manage_balances': 'Manage your balances and transactions',
      'actions_for': 'Actions for',
      'add_funds': 'Add Funds (Deposit)',
      'deposit': 'Deposit',
      'balance_available': 'Available Balance',
      'no_currencies': 'No currencies available',
      'deposit_requests': 'Deposit Requests',
      'status': 'Status',
      'amount': 'Amount',
      'date': 'Date',
      'invoice': 'Invoice',
      'id': 'ID',
      'bank': 'Bank',
      'fees': 'Fees',
      'tax': 'Tax',
      'approved': 'Approved',
      'reference': 'Reference | ID',

      // Addresses Tab
      'addresses': 'Addresses',
      'my_addresses': 'My Addresses',
      'add_address': 'Add Address',
      'copy': 'Copy',
      'copied': 'Copied',
      'no_addresses': 'No addresses yet',

      // Settings Tab
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'Select Language',
      'about': 'About',
      'version': 'Version',
      'logout': 'Logout',

      // Request Flow
      'payment_request': 'Payment Request',
      'generate_request': 'Generate Request',
      'requesting': 'Requesting...',
      'valid_until': 'Valid Until',
      'note': 'Note',
      'select_purpose_request': 'Select Purpose Of Money Request',
      'cannot_use_after_expiry': 'Will Not Be Able To Use The Code After Its Expiry Time',
      'purpose_of_request': 'Purpose Of Money Request',
      'always': 'Always',
      'minutes_3': '3 Minute',
      'minutes_15': '15 Minute',
      'hour_1': '1 Hour',
      'hours_24': '24 Hour',
      'work_partnership': 'Work/Partnership',
      'service_fees': 'Service Fees',
      'home_rent': 'Home Rent',
      'office_shop_rent': 'Office / Shop Rent',
      'deposit_request': 'Deposit Request',
      'enter_amount': 'Enter Amount',
      'enter_reference': 'Enter Reference | ID',
      'enter_note_receiver': 'Enter Your Note To See On Receiver Account',

      // Send Flow
      'transfer_send': 'Transfer / Send',
      'sender_account': 'Sender Account',
      'send_to': 'Send To',
      'recipient_account': 'Recipient Account',
      'recipient_phone': 'Recipient Phone',
      'enter_account_or_phone': 'Enter Account or Phone',
      'recipient_name_id': 'Recipient Name | ID',
      'recipient_id_num': 'Recipient ID Number',
      'amount_to_be_sent': 'Amount to be sent',
      'purpose_of_send': 'Purpose of send',
      'money_sent_success': 'Money sent successfully',
      'transaction_failed': 'Transaction failed',
      'receipt': 'Receipt',

      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'ok': 'OK',
      'safe': 'Safe',
      'powered_by': 'Powered By',
      'failed_to_load': 'Failed to load',
      'try_again': 'Try again',
      'success': 'Success',
      'source_bank': 'Source Bank',
      'select_bank': 'Select a bank...',
      'load_more': 'Load more',
      'amount_label': 'Amount',
      'complete_form_deposit': 'Complete the form to request a deposit.',
      'deposit_symbol': 'Deposit',
      'fee_label': 'Fee:',
      'tax_label': 'Tax:',
      'you_receive': 'You Receive:',
      'proof_of_transfer': 'Proof of Transfer',
      'click_to_upload': 'Click to upload image',
      'upload_success_msg': 'Upload successful',
      'change_image': 'Change image',
      'uploading_msg': 'Uploading...',
      'confirm_upload': 'Confirm upload',
      'confirm_deposit_label': 'Confirm Deposit',
      'deposit_request_submitted': 'Deposit request submitted successfully',
      'deposit_completed_success': 'Deposit completed successfully',
      'failed_to_submit_deposit': 'Failed to submit deposit request',
      'failed_to_load_banks': 'Failed to load banks',
      'page': 'Page',
      'of': 'of',
      'done': 'Done',
      'copy_clipboard': 'Copied to clipboard',
      'failed_to_save': 'Failed to save QR Card.',
      'saved_successfully': 'QR Card saved to gallery successfully!',
      'download': 'Download',
      'share': 'Share',
      'account_name': 'Account Name',
      'account_number': 'Account Number',
      'date_time': 'Date & Time',
      'type': 'Type',
      'succeeded': 'Succeeded',
      'american_dollars': 'American Dollars',
      'until': 'until',
      'payment_request_for': 'Payment Request for {amount} {currency}',
      'main_sub_account': 'Main',
      'deposit_type': 'Deposit',
      'withdrawal_type': 'Withdrawal',
      'refund_type': 'Refund',
      'order_type': 'Order',
      'invoice_type': 'Invoice',
      'receipt_footer_msg':
          'You Can Receive The Money Through All Our Centers, Or You Can Download Our Application, Open An Account, Use The Money, And Benefit From All The Services.',
      'statistic': 'Statistic',
      'info': 'Info',
      'scan_qr_msg': 'Read The Code On The Opposite Side To Take Action',
      'or_choose': 'Or Choose',
      'send_pay_cash': 'Send | Pay | Cash Withdrawal',
      'send_money_pay': 'Send Money Or Pay',
      'receive_charge_request': 'Receive | Charge My Account | Request',
      'charge_wallet_msg': 'Charge Your Wallet Account Money',
      'splash_safe': 'safe...',
      'splash_easy': 'easy...',
      'splash_transaction': 'transaction...',
      'splash_payment': 'payment...',
      'acc_copied_msg': 'Account number copied to clipboard',
      'my_receipt_qr': 'My Receipt Account QR',
      'request': 'Request',
      'send_pay_cash_upper': 'SEND | PAY | CASH WITHDRAWAL',
      'transfer_send_msg': 'Send | Transfer Money To rdb | cash | bank',
      'history': 'History',
      'cash_withdrawal': 'Cash Withdrawal',
      'withdrawal_msg': 'Withdrawal Via Our Centers Or Agents',
      'nearby_centers': 'Nearby Centers',
      'bill_payments': 'Bill Payments',
      'pay_invoice_msg': 'Pay Invoice | Bill |',
      'jan': 'Jan',
      'feb': 'Feb',
      'mar': 'March',
      'apr': 'April',
      'may': 'May',
      'jun': 'June',
      'jul': 'July',
      'aug': 'August',
      'sep': 'Sept',
      'oct': 'Oct',
      'nov': 'Nov',
      'dec': 'Dec',
      'invalid_amount': 'Invalid Amount',
      'insufficient_balance': 'Insufficient Balance',
      'incorrect_account_msg':
          'Incorrect Account Number. It Should Start With 1 And Consist Of 6 Digits',
      'phone_min_digits_msg': 'Phone number must be at least 7 digits',
      'recipient_account_num': 'Recipient Account Number',
      'recipient_phone_num': 'Recipient Phone Number',
      'paste': 'Paste',
      'office': 'Office',
      'enter_recipient_acc': 'Enter Recipient Account Number',
      'enter_recipient_phone': 'Enter Recipient Phone Number',
      'enter_recipient_name': 'Enter Recipient Name & Surname Exact ID',
      'enter_recipient_id': 'Enter Recipient ID NUMBER',
      'recipient_name_hint': 'Mohamad Ramzi Katmawi',
      'recipient_id_hint': 'ID Card Or Passport Or Driving License Number',
      'enter': 'Enter ',
      'or': ' Or    ',
      'edit': 'Edit',
      'sending': 'Sending...',
      'send_deposits': 'Send Deposits',
      'expired_code': 'Expired Code ( Time Expired )',
      'reference_id': 'Reference | ID',
      'minutes_until': ' Minutes Until ',
      'select_purpose_send': 'Select Purpose Of Money Send',
      'send_label': 'Send',
      'receive_label': 'Receive',
    },
    'ar': {
      // Home Tab
      'home_title': 'الرئيسية',
      'total_balance': 'إجمالي رصيدك',
      'add_currency': 'إضافة عملة',
      'available_balance': 'الرصيد المتاح',
      'records': 'السجلات',
      'no_deposit_requests_yet': 'لا توجد طلبات إيداع حتى الآن',
      'all_transactions': 'جميع المعاملات',
      'your_total_balance': 'إجمالي رصيدك',
      'balance': 'الرصيد',
      'transaction_history': 'سجل المعاملات',
      'no_transactions': 'لا توجد معاملات حتى الآن',
      'recent_transactions': 'المعاملات الأخيرة',
      'view_all': 'عرض الكل',
      'your_total_balance_of': 'إجمالي رصيد {currency} الخاص بك',
      'add_account_of': 'إضافة حساب {currency}',

      // Wallet Tab
      'my_wallet': 'محفظتي',
      'manage_balances': 'إدارة أرصدتك والمعاملات',
      'actions_for': 'الإجراءات لـ',
      'add_funds': 'إضافة أموال (إيداع)',
      'deposit': 'إيداع',
      'balance_available': 'الرصيد المتاح',
      'no_currencies': 'لا توجد عملات متاحة',
      'deposit_requests': 'طلبات الإيداع',
      'status': 'الحالة',
      'amount': 'المبلغ',
      'date': 'التاريخ',
      'pending': 'قيد الانتظار',
      'completed': 'مكتمل',
      'failed': 'فشل',
      'withdrawal': 'سحب',
      'refund': 'استرداد',
      'order': 'طلب',
      'invoice': 'فاتورة',
      'id': 'المعرف',
      'bank': 'البنك',
      'fees': 'الرسوم',
      'tax': 'الضريبة',

      // Addresses Tab
      'addresses': 'العناوين',
      'my_addresses': 'عناويني',
      'add_address': 'إضافة عنوان',
      'copy': 'نسخ',
      'copied': 'تم النسخ',
      'no_addresses': 'لا توجد عناوين حتى الآن',

      // Settings Tab
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'اختر اللغة',
      'about': 'حول',
      'version': 'الإصدار',
      'logout': 'تسجيل الخروج',

      // Request Flow
      'payment_request': 'طلب دفع',
      'generate_request': 'إنشاء طلب',
      'requesting': 'جاري الطلب...',
      'valid_until': 'صالح حتى',
      'note': 'ملاحظة',
      'select_purpose_request': 'اختر الغرض من طلب المال',
      'cannot_use_after_expiry': 'لن يتم التمكن من استخدام الرمز بعد انتهاء وقت الصلاحية',
      'purpose_of_request': 'الغرض من طلب المال',
      'always': 'دائماً',
      'minutes_3': '3 دقائق',
      'minutes_15': '15 دقيقة',
      'hour_1': 'ساعة واحدة',
      'hours_24': '24 ساعة',
      'work_partnership': 'عمل / شراكة',
      'service_fees': 'رسوم الخدمة',
      'home_rent': 'إيجار منزل',
      'office_shop_rent': 'إيجار مكتب / محل',
      'deposit_request': 'طلب إيداع',
      'enter_amount': 'أدخل المبلغ',
      'enter_reference': 'أدخل المرجع | المعرف',
      'enter_note_receiver': 'أدخل ملاحظتك ليراها حساب المستلم',

      // Send Flow
      'transfer_send': 'تحويل / إرسال',
      'sender_account': 'حساب المرسل',
      'send_to': 'إرسال إلى',
      'recipient_account': 'حساب المستلم',
      'recipient_phone': 'رقم هاتف المستلم',
      'enter_account_or_phone': 'أدخل الحساب أو رقم الهاتف',
      'recipient_name_id': 'اسم المستلم | المعرف',
      'recipient_id_num': 'رقم المعرف للمستلم',
      'amount_to_be_sent': 'المبلغ المراد إرساله',
      'purpose_of_send': 'الغرض من الإرسالية',
      'money_sent_success': 'تم إرسال الأموال بنجاح',
      'transaction_failed': 'فشلت المعاملة',
      'receipt': 'إيصال',

      // Common
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'retry': 'إعادة محاولة',
      'cancel': 'إلغاء',
      'ok': 'حسناً',
      'safe': 'آمن',
      'powered_by': 'مدعوم من',
      'failed_to_load': 'فشل التحميل',
      'try_again': 'حاول مرة أخرى',
      'success': 'نجح',
      'source_bank': 'البنك المصدر',
      'select_bank': 'اختر بنكاً...',
      'load_more': 'تحميل المزيد',
      'amount_label': 'المبلغ',
      'complete_form_deposit': 'أكمل النموذج لطلب الإيداع.',
      'deposit_symbol': 'إيداع',
      'fee_label': 'الرسوم:',
      'tax_label': 'الضريبة:',
      'you_receive': 'ستستلم:',
      'proof_of_transfer': 'إثبات الحوالة',
      'click_to_upload': 'اضغط لرفع صورة',
      'upload_success_msg': 'تم الرفع بنجاح',
      'change_image': 'تغيير الصورة',
      'uploading_msg': 'جاري الرفع...',
      'confirm_upload': 'تأكيد الرفع',
      'confirm_deposit_label': 'تأكيد الإيداع',
      'deposit_request_submitted': 'تم تقديم طلب الإيداع بنجاح',
      'deposit_completed_success': 'تم اكتمال الإيداع بنجاح',
      'failed_to_submit_deposit': 'فشل في تقديم طلب الإيداع',
      'failed_to_load_banks': 'فشل في تحميل البنوك',
      'page': 'صفحة',
      'of': 'من',
      'done': 'تم',
      'copy_clipboard': 'نسخ إلى الحافظة',
      'failed_to_save': 'فشل في الحفظ',
      'saved_successfully': 'تم الحفظ بنجاح',
      'download': 'تحميل',
      'share': 'مشاركة',
      'account_name': 'اسم الحساب',
      'account_number': 'رقم الحساب',
      'date_time': 'التاريخ والوقت',
      'type': 'النوع',
      'succeeded': 'نجحت',
      'american_dollars': 'دولارات أمريكية',
      'receipt_footer_msg':
          'يمكنك استلام الأموال من خلال جميع مراكزنا، أو يمكنك تحميل تطبيقنا، وفتح حساب، واستخدام الأموال، والاستفادة من جميع الخدمات.',
      'statistic': 'الإحصائيات',
      'info': 'معلومات',
      'approved': 'مقبول',
      'reference': 'المرجع | المعرف',
      'scan_qr_msg': 'اقرأ الكود في الجهة المقابلة لاتخاذ إجراء',
      'or_choose': 'أو اختر',
      'send_pay_cash': 'إرسال | دفع | سحب نقدي',
      'send_money_pay': 'إرسال أموال أو دفع',
      'receive_charge_request': 'استلام | شحن حسابي | طلب',
      'charge_wallet_msg': 'شحن أموال حساب محفظتك',
      'splash_safe': 'آمن...',
      'splash_easy': 'سهل...',
      'splash_transaction': 'معاملة...',
      'splash_payment': 'دفع...',
      'acc_copied_msg': 'تم نسخ رقم الحساب إلى الحافظة',
      'my_receipt_qr': 'QR حساب الإيصال الخاص بي',
      'request': 'طلب',
      'send_pay_cash_upper': 'إرسال | دفع | سحب نقدي',
      'transfer_send_msg': 'إرسال | تحويل أموال إلى rdb | نقداً | بنك',
      'history': 'السجل',
      'cash_withdrawal': 'سحب نقدي',
      'withdrawal_msg': 'سحب من خلال مراكزنا أو وكلائنا',
      'nearby_centers': 'المراكز القريبة',
      'bill_payments': 'دفع الفواتير',
      'pay_invoice_msg': 'دفع فاتورة | إيصال |',
      'jan': 'يناير',
      'feb': 'فبراير',
      'mar': 'مارس',
      'apr': 'أبريل',
      'may': 'مايو',
      'jun': 'يونيو',
      'jul': 'يوليو',
      'aug': 'أغسطس',
      'sep': 'سبتمبر',
      'oct': 'أكتوبر',
      'nov': 'نوفمبر',
      'dec': 'ديسمبر',
      'invalid_amount': 'مبلغ غير صحيح',
      'insufficient_balance': 'رصيد غير كافٍ',
      'incorrect_account_msg':
          'رقم الحساب غير صحيح. يجب أن يبدأ بـ 1 ويتكون من 6 أرقام',
      'phone_min_digits_msg': 'رقم الهاتف يجب أن يتكون من 7 أرقام على الأقل',
      'recipient_account_num': 'رقم حساب المستلم',
      'recipient_phone_num': 'رقم هاتف المستلم',
      'paste': 'لصق',
      'office': 'مكتب',
      'enter_recipient_acc': 'أدخل رقم حساب المستلم',
      'enter_recipient_phone': 'أدخل رقم هاتف المستلم',
      'enter_recipient_name': 'أدخل اسم المستلم واللقب تماماً كما في الهوية',
      'enter_recipient_id': 'أدخل رقم هوية المستلم',
      'recipient_name_hint': 'محمد رمزي كتماوي',
      'recipient_id_hint': 'رقم الهوية أو جواز السفر أو رخصة القيادة',
      'enter': 'أدخل ',
      'or': ' أو    ',
      'edit': 'تعديل',
      'sending': 'جاري الإرسال...',
      'send_deposits': 'إرسال الإيداع',
      'expired_code': 'رمز منتهي الصلاحية (الوقت انتهى)',
      'reference_id': 'المرجع | المعرف',
      'minutes_until': ' دقائق حتى ',
      'select_purpose_send': 'اختر الغرض من إرسال المال',
      'send_label': 'إرسال',
      'receive_label': 'استلام',
      'until': 'حتى',
      'payment_request_for': 'طلب دفع بـ {amount} {currency}',
      'main_sub_account': 'الأساسي',
      'deposit_type': 'إيداع',
      'withdrawal_type': 'سحب',
      'refund_type': 'استرداد',
      'order_type': 'طلب',
      'invoice_type': 'فاتورة',
    },
    'ku': {
      // Home Tab
      'home_title': 'سەرەتا',
      'total_balance': 'کۆی بەروونی تۆ',
      'add_currency': 'موژدە سازی زیادکە',
      'all_transactions': 'هەموو وەرگێڕانەکان',
      'available_balance': 'بەروونی دەستدەست',
      'records': 'تۆمارەکان',
      'no_deposit_requests_yet': 'هێشتا هیچ داواکاری داخواڵێک نیە',
      'balance': 'بەروونی',
      'transaction_history': 'مێژووی وەرگێڕانەکان',
      'no_transactions': 'هیچ وەرگێڕانەی تێدا نیە',
      'recent_transactions': 'وەرگێڕانە نوێیەکان',
      'your_total_balance': 'کۆی بەروونی تۆ',
      'view_all': 'هەمووی ببینە',
      'your_total_balance_of': 'کۆی باڵانسی {currency} تۆ',
      'add_account_of': 'زیادکردنی هەژماری {currency}',

      // Wallet Tab
      'my_wallet': 'کیسەی من',
      'manage_balances': 'بەڕێوەبردنی بەروونی و وەرگێڕانەکان',
      'actions_for': 'کردارەکان بۆ',
      'add_funds': 'زیادکردنی پارە (داخواڵ)',
      'deposit': 'داخواڵ',
      'balance_available': 'بەروونی دەستدەست',
      'no_currencies': 'موژدە سازێی بەردەست نیە',
      'deposit_requests': 'داواکاری داخواڵ',
      'status': 'دۆخ',
      'amount': 'بەرھەم',
      'date': 'بەرواری',
      'pending': 'چاوەڕۆیان کردن',
      'completed': 'تێچوو',
      'failed': 'شکست',
      'withdrawal': 'ڕاکێشان',
      'refund': 'گێڕانەوە',
      'order': 'داواکاری',
      'invoice': 'وەسڵ',
      'id': 'ناسنامە',
      'bank': 'بانک',
      'fees': 'ڕسوومات',
      'tax': 'باج',
      'approved': 'پەسەندکراوە',
      'reference': 'سەرچاوە | ناسنامە',

      // Addresses Tab
      'addresses': 'ناونیشانەکان',
      'my_addresses': 'ناونیشانەکانی من',
      'add_address': 'زیادکردنی ناونیشان',
      'copy': 'کۆپی',
      'copied': 'کۆپی کرا',
      'no_addresses': 'هیچ ناونیشانی تێدا نیە',

      // Settings Tab
      'settings': 'ڕێکخستنەکان',
      'language': 'زمان',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'زمانی هەڵبژێرە',
      'about': 'دەربارەی',
      'version': 'وەشان',
      'logout': 'دەرچوون',

      // Request Flow
      'payment_request': 'داواکاری پارەدان',
      'generate_request': 'دروستکردنی داواکاری',
      'requesting': 'جاري داواكردن...',
      'valid_until': 'بەردەستە تا',
      'note': 'تێبینی',
      'select_purpose_request': 'هۆکاری داواکاری پارە هەڵبژێرە',
      'cannot_use_after_expiry': 'ناتوانی کۆدەکە بەکاربهێنیت دوای بەسەرچوونی کاتەکەی',
      'purpose_of_request': 'هۆکاری داواکاری پارە',
      'always': 'هەمیشە',
      'minutes_3': '٣ خولەک',
      'minutes_15': '١٥ خولەک',
      'hour_1': '١ کاتژمێر',
      'hours_24': '٢٤ خولەک',
      'work_partnership': 'کار / هاوبەشی',
      'service_fees': 'ڕسوومات خزمەتگوزاری',
      'home_rent': 'کرێی خانوو',
      'office_shop_rent': 'کرێی نووسینگە / دوکان',
      'deposit_request': 'داواکاری داخیڵکردن',
      'enter_amount': 'بڕ بنووسە',
      'enter_reference': 'سەرچاوە | ناسنامە بنووسە',
      'enter_note_receiver': 'تێبینی بنووسە بۆ هەژماری وەرگر',

      // Send Flow
      'transfer_send': 'گواستنەوە / ناردن',
      'sender_account': 'هەژماری نێرەر',
      'send_to': 'ناردن بۆ',
      'recipient_account': 'هەژماری وەرگر',
      'recipient_phone': 'ژمارەی مۆبایلی وەرگر',
      'enter_account_or_phone': 'هەژمار یان ژمارەی مۆبایل بنووسە',
      'recipient_name_id': 'ناوی وەرگر | ناسنامە',
      'recipient_id_num': 'ژمارەی ناسنامەی وەرگر',
      'amount_to_be_sent': 'بڕی پارەی نێردراو',
      'purpose_of_send': 'هۆکاری ناردن',
      'money_sent_success': 'پارەکە بە سەرکەوتوویی نێردرا',
      'transaction_failed': 'مامەڵەکە شکستی هێنا',
      'receipt': 'وەسڵ',

      // Common
      'loading': 'بارکردن...',
      'error': 'هەڵە',
      'retry': 'هەوڵ دووبارە',
      'cancel': 'پاشگەزبوونەوە',
      'ok': 'باشە',
      'safe': 'ئیمن',
      'powered_by': 'پشتگیری',
      'failed_to_load': 'بارکردن شکست',
      'try_again': 'دووبارە هەوڵ بدە',
      'success': 'سەرکەوتوو',
      'source_bank': 'بانکی سەرچاوە',
      'select_bank': 'بانکێ هەڵبژێرە...',
      'load_more': 'زیاتر بەرزبکەرەوە',
      'amount_label': 'بڕی',
      'complete_form_deposit': 'تکایە فۆرمەکە پڕبکەرەوە بۆ داواکاری داخیڵکردن.',
      'deposit_symbol': 'داخیڵکردن',
      'fee_label': 'ڕسوومات:',
      'tax_label': 'باج:',
      'you_receive': 'تۆ وەردەگریت:',
      'proof_of_transfer': 'بەڵگەی گواستنەوە',
      'click_to_upload': 'کلیک بکە بۆ بەرزکردنەوەی وێنە',
      'upload_success_msg': 'بەرزکردنەوە سەرکەوتوو بوو',
      'change_image': 'وێنەکە بگۆڕە',
      'uploading_msg': 'جاری بەرزکردنەوەیە...',
      'confirm_upload': 'بەرزکردنەوە پشتڕاست بکەرەوە',
      'confirm_deposit_label': 'داخیڵکردن پشتڕاست بکەرەوە',
      'deposit_request_submitted': 'داواکاری داخیڵکردن بە سەرکەوتوویی نێردرا',
      'deposit_completed_success': 'داخیڵکردن بە سەرکەوتوویی تەواو بوو',
      'failed_to_submit_deposit': 'ناردنی داواکاری داخیڵکردن شکستی هێنا',
      'failed_to_load_banks': 'بارکردنی بانکەکان شکستی هێنا',
      'page': 'لاپەڕە',
      'of': 'لە',
      'done': 'تەواو',
      'copy_clipboard': 'کۆپی کرا بۆ کلیپبۆرد',
      'failed_to_save': 'پاشکەوتکردن شکستی هێنا',
      'saved_successfully': 'بە سەرکەوتوویی پاشکەوت کرا',
      'download': 'داگرتن',
      'share': 'هاوبەشکردن',
      'account_name': 'ناوی هەژمار',
      'account_number': 'ژمارەی هەژمار',
      'date_time': 'بەروار و کات',
      'type': 'جۆر',
      'succeeded': 'سەرکەوتوو بوو',
      'american_dollars': 'دۆلاری ئەمریکی',
      'receipt_footer_msg':
          'دەتوانیت پارەکە لە ڕێگەی هەموو سەنتەرەكانمانەوە وەربگریت، یان دەتوانیت ئەپڵیکەیشنەکەمان دابەزێنیت، هەژمارێک بكەیتەوە، پارەکە بەکاربهێنیت، و سوود لە هەموو خزمەتگوزارییەکان وەربگریت.',
      'statistic': 'ئامارەكان',
      'info': 'زانیاری',
      'scan_qr_msg': 'بۆ ئەوەی کردارێک ئەنجام بدەیت، کۆدەکە لە لای بەرامبەر بخوێنەرەوە',
      'or_choose': 'یان هەڵبژێرە',
      'send_pay_cash': 'ناردن | پارەدان | ڕاكێشانی کاش',
      'send_money_pay': 'ناردنی پارە یان پارەدان',
      'receive_charge_request': 'وەرگرتن | بارگاویکردنەوەی هەژمارەکەم | داواکاری',
      'charge_wallet_msg': 'بارگاویکردنەوەی پارەی هەژماری جزدانەکەت',
      'splash_safe': 'پارێزراو...',
      'splash_easy': 'ئاسان...',
      'splash_transaction': 'مامەڵە...',
      'splash_payment': 'پارەدان...',
      'acc_copied_msg': 'ژمارەی هەژمارەکە کۆپی کرا بۆ کلیپبۆرد',
      'my_receipt_qr': 'QR ی هەژماری وەسڵەکەم',
      'request': 'داواکاری',
      'send_pay_cash_upper': 'ناردن | پارەدان | ڕاکێشانی کاش',
      'transfer_send_msg': 'ناردن | گواستنەوەی پارە بۆ rdb | کاش | بانک',
      'history': 'مێژوو',
      'cash_withdrawal': 'ڕاکێشانی کاش',
      'withdrawal_msg': 'ڕاکێشان لە ڕێگەی سەنتەرەکانمان یان بریکارەکانمان',
      'nearby_centers': 'سەنتەرە نزیکەکان',
      'bill_payments': 'پارەدانی پسوولەکان',
      'pay_invoice_msg': 'پارەدانی وەسڵ | پسوولە |',
      'jan': 'کانوونی دووەم',
      'feb': 'شوبات',
      'mar': 'ئازار',
      'apr': 'نیسان',
      'may': 'ئایار',
      'jun': 'حوزەیران',
      'jul': 'تەممووز',
      'aug': 'ئاب',
      'sep': 'ئەیلوول',
      'oct': 'تشرینی یەکەم',
      'nov': 'تشرینی دووەم',
      'dec': 'کانوونی یەکەم',
      'invalid_amount': 'بڕی نادروست',
      'insufficient_balance': 'باڵانسی تەواو نییە',
      'incorrect_account_msg':
          'ژمارەی هەژمارەکە هەڵەیە. دەبێت بە ١ دەست پێ بکات و لە ٦ ژمارە پێک بێت',
      'phone_min_digits_msg': 'ژمارەی تەلەفۆن دەبێت لانی کەم ٧ ژمارە بێت',
      'recipient_account_num': 'ژمارەی هەژماری وەرگر',
      'recipient_phone_num': 'ژمارەی تەلەفۆنی وەرگر',
      'paste': 'لکاندن',
      'office': 'نووسینگە',
      'enter_recipient_acc': 'ژمارەی هەژماری وەرگر داخڵ بکە',
      'enter_recipient_phone': 'ژمارەی تەلەفۆنی وەرگر داخڵ بکە',
      'enter_recipient_name': 'ناوی وەرگر و نازناوی وەرگر بە وردی وەک ناسنامە',
      'enter_recipient_id': 'ژمارەی ناسنامەی وەرگر داخڵ بکە',
      'recipient_name_hint': 'محەمەد ڕەمزی کەتماوی',
      'recipient_id_hint': 'ژمارەی ناسنامە یان پاسپۆرت یان مۆڵەتی شۆفێری',
      'enter': 'داخڵ بکرێت ',
      'or': ' یان    ',
      'edit': 'دەستکاریکردن',
      'sending': 'جاری ناردنە...',
      'send_deposits': 'ناردنی داواکاری داخیڵکردن',
      'expired_code': 'کۆدی بەسەرچوو (کاتی تەواو بوو)',
      'reference_id': 'سەرچاوە | ناسنامە',
      'minutes_until': ' خولەک تاوەکو ',
      'select_purpose_send': 'هۆکاری ناردنی پارە هەڵبژێرە',
      'send_label': 'ناردن',
      'receive_label': 'وەرگرتن',
      'until': 'تاوەکو',
      'payment_request_for': 'داواکاری پارەدان بڕی {amount} {currency}',
      'main_sub_account': 'سەرەکی',
      'deposit_type': 'داخیڵکردن',
      'withdrawal_type': 'ڕاکێشان',
      'refund_type': 'گێڕانەوە',
      'order_type': 'داواکاری',
      'invoice_type': 'وەسڵ',
    },
    'tr': {
      // Home Tab
      'home_title': 'Anasayfa',
      'total_balance': 'Toplam Bakiyeniz',
      'add_currency': 'Para Birimi Ekle',
      'all_transactions': 'Tüm İşlemler',
      'balance': 'Bakiye',
      'your_total_balance': 'Toplam Bakiyeniz',
      'available_balance': 'Mevcut Bakiye',
      'records': 'Kayıtlar',
      'no_deposit_requests_yet': 'Henüz hiçbir yatırma talebi yok',
      'transaction_history': 'İşlem Geçmişi',
      'no_transactions': 'Henüz hiçbir işlem yok',
      'recent_transactions': 'Son İşlemler',
      'view_all': 'Tümünü Görüntüle',
      'your_total_balance_of': 'Toplam {currency} Bakiyeniz',
      'add_account_of': '{currency} Hesabı Ekle',

      // Wallet Tab
      'my_wallet': 'Cüzdanım',
      'manage_balances': 'Bakiyelerinizi ve işlemlerinizi yönetin',
      'actions_for': 'İçin İşlemler',
      'add_funds': 'Para Ekle (Yatırma)',
      'deposit': 'Yatırma',
      'balance_available': 'Mevcut Bakiye',
      'no_currencies': 'Kullanılabilir para birimi yok',
      'deposit_requests': 'Yatırma Talepleri',
      'status': 'Durum',
      'amount': 'Tutar',
      'date': 'Tarih',
      'pending': 'Beklemede',
      'completed': 'Tamamlandı',
      'failed': 'Başarısız',
      'withdrawal': 'Para Çekme',
      'refund': 'İade',
      'order': 'Sipariş',
      'invoice': 'Fatura',
      'id': 'ID',
      'bank': 'Banka',
      'fees': 'Ücretler',
      'tax': 'Vergi',
      'approved': 'Onaylandı',
      'reference': 'Referans | ID',

      // Addresses Tab
      'addresses': 'Adresler',
      'my_addresses': 'Adreslerim',
      'add_address': 'Adres Ekle',
      'copy': 'Kopyala',
      'copied': 'Kopyalandı',
      'no_addresses': 'Henüz hiçbir adres yok',

      // Settings Tab
      'settings': 'Ayarlar',
      'language': 'Dil',
      'english': 'English',
      'arabic': 'العربية',
      'kurdish': 'کوردی',
      'turkish': 'Türkçe',
      'select_language': 'Dili Seçin',
      'about': 'Hakkında',
      'version': 'Sürüm',
      'logout': 'Çıkış Yap',

      // Request Flow
      'payment_request': 'Ödeme Talebi',
      'generate_request': 'Talep Oluştur',
      'requesting': 'Talep ediliyor...',
      'valid_until': 'Geçerlilik Süresi',
      'note': 'Not',
      'select_purpose_request': 'Para Talep Amacını Seçin',
      'cannot_use_after_expiry': 'Süresi dolduktan sonra kod kullanılamayacaktır',
      'purpose_of_request': 'Para Talep Amacı',
      'always': 'Her zaman',
      'minutes_3': '3 Dakika',
      'minutes_15': '15 Dakika',
      'hour_1': '1 Saat',
      'hours_24': '24 Saat',
      'work_partnership': 'İş / Ortaklık',
      'service_fees': 'Hizmet Ücretleri',
      'home_rent': 'Ev Kirası',
      'office_shop_rent': 'Ofis / Dükkan Kirası',
      'deposit_request': 'Para Yatırma Talebi',
      'enter_amount': 'Tutarı Girin',
      'enter_reference': 'Referans | ID Girin',
      'enter_note_receiver': 'Alıcı hesabında görünecek notu girin',

      // Send Flow
      'transfer_send': 'Transfer / Gönder',
      'sender_account': 'Gönderen Hesabı',
      'send_to': 'Şuna Gönder',
      'recipient_account': 'Alıcı Hesabı',
      'recipient_phone': 'Alıcı Telefon Numarası',
      'enter_account_or_phone': 'Hesap veya Telefon Numarası Girin',
      'recipient_name_id': 'Alıcı Adı | ID',
      'recipient_id_num': 'Alıcı ID Numarası',
      'amount_to_be_sent': 'Gönderilecek Tutar',
      'purpose_of_send': 'Gönderim Amacı',
      'money_sent_success': 'Para başarıyla gönderildi',
      'transaction_failed': 'İşlem başarısız oldu',
      'receipt': 'Makbuz',

      // Common
      'loading': 'Yükleniyor...',
      'error': 'Hata',
      'retry': 'Yeniden Dene',
      'cancel': 'İptal',
      'ok': 'Tamam',
      'safe': 'Güvenli',
      'powered_by': 'Tarafından Destekleniyor',
      'failed_to_load': 'Yükleme Başarısız',
      'try_again': 'Tekrar Deneyin',
      'success': 'Başarılı',
      'source_bank': 'Kaynak Banka',
      'select_bank': 'Bir banka seçin...',
      'load_more': 'Daha fazla yükle',
      'amount_label': 'Miktar',
      'complete_form_deposit': 'Para yatırma talebi için formu doldurun.',
      'deposit_symbol': 'Para Yatırma',
      'fee_label': 'Ücret:',
      'tax_label': 'Vergi:',
      'you_receive': 'Alacağınız Tutar:',
      'proof_of_transfer': 'Transfer Kanıtı',
      'click_to_upload': 'Resim yüklemek için tıklayın',
      'upload_success_msg': 'Yükleme başarılı',
      'change_image': 'Resmi değiştir',
      'uploading_msg': 'Yükleniyor...',
      'confirm_upload': 'Yüklemeyi onayla',
      'confirm_deposit_label': 'Para Yatırmayı Onayla',
      'deposit_request_submitted': 'Yatırma talebi başarıyla iletildi',
      'deposit_completed_success': 'Yatırma başarıyla tamamlandı',
      'failed_to_submit_deposit': 'Yatırma talebi iletilemedi',
      'failed_to_load_banks': 'Bankalar yüklenemedi',
      'page': 'Sayfa',
      'of': '/',
      'done': 'Tamam',
      'copy_clipboard': 'Panoya kopyalandı',
      'failed_to_save': 'Kaydedilemedi',
      'saved_successfully': 'Başarıyla kaydedildi',
      'download': 'İndir',
      'share': 'Paylaş',
      'account_name': 'Hesap Adı',
      'account_number': 'Hesap Numarası',
      'date_time': 'Tarih ve Saat',
      'type': 'Tür',
      'succeeded': 'Başarılı',
      'american_dollars': 'Amerikan Doları',
      'receipt_footer_msg':
          'Parayı tüm merkezlerimizde alabilir veya uygulamamızı indirip hesap açarak parayı kullanabilir ve tüm hizmetlerden yararlarbilirsiniz.',
      'statistic': 'İstatistik',
      'info': 'Bilgi',
      'scan_qr_msg': 'Harekete geçmek için karşı taraftaki kodu okuyun',
      'or_choose': 'Veya Seçin',
      'send_pay_cash': 'Gönder | Öde | Nakit Çekme',
      'send_money_pay': 'Para Gönder veya Öde',
      'receive_charge_request': 'Al | Hesabımı Yükle | İstek',
      'charge_wallet_msg': 'Cüzdan hesabınıza para yükleyin',
      'splash_safe': 'güvenli...',
      'splash_easy': 'kolay...',
      'splash_transaction': 'işlem...',
      'splash_payment': 'ödeme...',
      'acc_copied_msg': 'Hesap numarası panoya kopyalandı',
      'my_receipt_qr': 'Makbuz Hesabım QR',
      'request': 'İstek',
      'send_pay_cash_upper': 'GÖNDER | ÖDE | NAKİT ÇEKME',
      'transfer_send_msg': 'Gönder | rdb | nakit | bankaya para transferi yap',
      'history': 'Geçmiş',
      'cash_withdrawal': 'Nakit Çekme',
      'withdrawal_msg': 'Merkezlerimiz veya Acentelerimiz Aracılığıyla Para Çekme',
      'nearby_centers': 'Yakındaki Merkezler',
      'bill_payments': 'Fatura Ödemeleri',
      'pay_invoice_msg': 'Fatura Öde | Makbuz |',
      'jan': 'Ocak',
      'feb': 'Şubat',
      'mar': 'Mart',
      'apr': 'Nisan',
      'may': 'Mayıs',
      'jun': 'Haziran',
      'jul': 'Temmuz',
      'aug': 'Ağustos',
      'sep': 'Eylül',
      'oct': 'Ekim',
      'nov': 'Kasım',
      'dec': 'Aralık',
      'invalid_amount': 'Geçersiz Tutar',
      'insufficient_balance': 'Yetersiz Bakiye',
      'incorrect_account_msg':
          'Yanlış Hesap Numarası. 1 ile başlamalı ve 6 haneli olmalıdır',
      'phone_min_digits_msg': 'Telefon numarası en az 7 haneli olmalıdır',
      'recipient_account_num': 'Alıcı Hesap Numarası',
      'recipient_phone_num': 'Alıcı Telefon Numarası',
      'paste': 'Yapıştır',
      'office': 'Ofis',
      'enter_recipient_acc': 'Alıcı Hesap Numarasını Girin',
      'enter_recipient_phone': 'Alıcı Telefon Numarasını Girin',
      'enter_recipient_name': 'Alıcı Adı ve Soyadını Kimlikteki Gibi Tam Girin',
      'enter_recipient_id': 'Alıcı Kimlik Numarasını Girin',
      'recipient_name_hint': 'Mohamad Ramzi Katmawi',
      'recipient_id_hint': 'Kimlik Kartı veya Pasaport veya Ehliyet Numarası',
      'enter': 'Girin ',
      'or': ' Veya    ',
      'edit': 'Düzenle',
      'sending': 'Gönderiliyor...',
      'send_deposits': 'Emanetleri Gönder',
      'expired_code': 'Süresi Dolmuş Kod (Zaman Doldu)',
      'reference_id': 'Referans | ID',
      'minutes_until': ' Dakika Kaldı ',
      'select_purpose_send': 'Para Gönderim Amacını Seçin',
      'send_label': 'Gönder',
      'receive_label': 'Al',
      'until': 'kadar',
      'payment_request_for': '{amount} {currency} için ödeme talebi',
      'main_sub_account': 'Ana',
      'deposit_type': 'Yatırma',
      'withdrawal_type': 'Çekme',
      'refund_type': 'İade',
      'order_type': 'Sipariş',
      'invoice_type': 'Fatura',
    },
  };

  /// Get localized string for the given key in the specified language
  static String get(String languageCode, String key) {
    final lang = _strings[languageCode];
    if (lang == null) {
      return _strings['en']![key] ?? key;
    }
    return lang[key] ?? _strings['en']![key] ?? key;
  }

  /// All supported languages
  static const List<String> supportedLanguages = ['en', 'ar', 'ku', 'tr'];
}
